export interface Product {
  id: string;
  name: string;
  image: string;
  description: string;
  type: 'Moisturizer' | 'Sunscreen' | 'Cleanser' | 'Serum' | 'Toner' | 'Face Wash' | 'Night Cream';
  suitableFor: string[];
  price: number;
  weatherCompatibility?: {
    hot?: boolean;
    cold?: boolean;
    humid?: boolean;
    dry?: boolean;
  };
  keyIngredients?: string[];
  benefits?: string[];
  routineType?: "Natural" | "Medical" | "Cosmetic";
}

export const products: Product[] = [
  // ALL SKIN TYPES - Moisturizers
  {
    id: 'ast-m-1',
    name: 'Cetaphil Daily Hydrating Lotion',
    description: 'Lightweight daily moisturizer with hyaluronic acid for all-day hydration.',
    price: 16.99,
    image: 'https://m.media-amazon.com/images/I/51U3KlUV8HL._SY355_.jpg',
    type: 'Moisturizer',
    suitableFor: ['All Skin Types'],
    weatherCompatibility: { hot: true, cold: true, humid: true, dry: true },
    keyIngredients: ['Hyaluronic Acid', 'Glycerin'],
    benefits: ['All-day hydration', 'Lightweight', 'Non-greasy'],
    routineType: 'Medical'
  },
  {
    id: 'ast-m-2',
    name: 'Neutrogena Hydro Boost Water Gel',
    description: 'Oil-free gel moisturizer with hyaluronic acid for instant hydration.',
    price: 18.99,
    image: 'https://m.media-amazon.com/images/I/51YTdG8RPSL._SY355_.jpg',
    type: 'Moisturizer',
    suitableFor: ['All Skin Types'],
    weatherCompatibility: { hot: true, humid: true, dry: true },
    keyIngredients: ['Hyaluronic Acid'],
    benefits: ['Oil-free', 'Instant hydration', 'Lightweight'],
    routineType: 'Medical'
  },
  {
    id: 'ast-m-3',
    name: 'La Roche-Posay Toleriane Double Repair',
    description: 'Prebiotic moisturizer that restores skin barrier with ceramides and niacinamide.',
    price: 19.99,
    image: 'https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcSbQ55AccU2OX2aRkmcNSIccOZEeg0_ZRm2YN8lMMUHz-4t-0yQL1jGbgXwZ_PmJLLQ4_MnNz9Bx0jngi3sP4iJhcFgmGhDs9rVwNkC0ua9mIfJOGGktrw9',
    type: 'Moisturizer',
    suitableFor: ['All Skin Types'],
    weatherCompatibility: { hot: true, cold: true, dry: true },
    keyIngredients: ['Ceramides', 'Niacinamide', 'Prebiotic'],
    benefits: ['Barrier repair', 'Prebiotic benefits', 'Calming'],
    routineType: 'Medical'
  },
  {
    id: 'ast-m-4',
    name: 'CeraVe AM / PM Moisturizing Lotion',
    description: 'Essential ceramides and hyaluronic acid for 24-hour hydration.',
    price: 15.99,
    image: 'https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcSe6-dvCd45gVvTmU2R27QV5vjbeyM04vmarcFrDqB1qbwWn1sjgqLxDbODXoyUkTUmfyGsVZtxgQIdsmYNM_xIxL4Ijt_uFx2b2ZU_U4dj3ikeRmoZxaGL',
    type: 'Moisturizer',
    suitableFor: ['All Skin Types'],
    weatherCompatibility: { hot: true, cold: true, humid: true, dry: true },
    keyIngredients: ['Ceramides', 'Hyaluronic Acid'],
    benefits: ['24-hour hydration', 'Barrier protection'],
    routineType: 'Medical'
  },
  {
    id: 'ast-m-5',
    name: 'Bioderma Atoderm Cream',
    description: 'Lightweight moisturizer for sensitive and dry skin with lipid-replenishing action.',
    price: 17.99,
    image: 'https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcSVbub3xU320onMNil9JzPZhnl4rxQC8FpZhFSt0LFlk4PBaAJxcjQ8-6dLCSilQEbO-9yrzW1E6V6RPB6tpIo6qnyx-HcBwzeclowJjkeXTosX3X9oHMwm',
    type: 'Moisturizer',
    suitableFor: ['All Skin Types'],
    weatherCompatibility: { cold: true, dry: true },
    keyIngredients: ['Lipid Complex'],
    benefits: ['Lipid replenishment', 'Soothing', 'Long-lasting comfort'],
    routineType: 'Medical'
  },

  // ALL SKIN TYPES - Cleansers
  {
    id: 'ast-c-1',
    name: 'CeraVe Hydrating Cleanser',
    description: 'Non-foaming cleanser that cleanses without stripping skin of natural moisture.',
    price: 13.99,
    image: 'https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcR4iHukrfYm4cG2POiBEZ1Yl2XNUOHilR8GOC5cWw_R46BDn-bQqUul46AoTcCWVTqpDsgc2s4uVy9aUh8xGWRMCzTw5JcQZQBGz7WTeONO1HfJIIMbH5s',
    type: 'Cleanser',
    suitableFor: ['All Skin Types'],
    weatherCompatibility: { hot: true, cold: true, humid: true, dry: true },
    keyIngredients: ['Ceramides', 'Hyaluronic Acid'],
    benefits: ['Gentle cleansing', 'Hydrating', 'Non-stripping'],
    routineType: 'Medical'
  },
  {
    id: 'ast-c-2',
    name: 'Cetaphil Gentle Skin Cleanser',
    description: 'Mild, non-irritating formula that soothes skin as it cleans.',
    price: 12.99,
    image: 'https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcRO5wAw0vHqWRuHewIrG6FfuyT0eY14vfP0SwAPv0zaVkfLKjidong49aY5D4mw30Gfq-S0gfuifvHryLacs5La1J8Qi0Juxd1Pdww0CItaFI5mRwP3jqlQVQptweqtr3g8pNHqRw&usqp=CAc',
    type: 'Cleanser',
    suitableFor: ['All Skin Types'],
    weatherCompatibility: { hot: true, cold: true, humid: true, dry: true },
    keyIngredients: ['Glycerin'],
    benefits: ['Gentle formula', 'Soothing', 'pH balanced'],
    routineType: 'Medical'
  },
  {
    id: 'ast-c-3',
    name: 'Simple Kind to Skin Facial Wash',
    description: 'No harsh chemicals, perfect for sensitive skin.',
    price: 8.99,
    image: 'https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcRNARYsH3fjUQBmM-9kyIiF2BTwOaJKzc_78WqmPJ5UPVzMKxpnR4j_bFc78nMQ0MsNPPxpJpdrnxzD53WeveCLOiNmPZE3uQS3z27CZDOS',
    type: 'Face Wash',
    suitableFor: ['All Skin Types'],
    weatherCompatibility: { hot: true, cold: true },
    keyIngredients: ['Vitamin B5', 'Vitamin E'],
    benefits: ['No harsh chemicals', 'Kind to skin', 'Gentle'],
    routineType: 'Natural'
  },
  {
    id: 'ast-c-4',
    name: 'Neutrogena Ultra Gentle Daily Cleanser',
    description: 'Ultra-gentle formula for everyday cleansing.',
    price: 10.99,
    image: 'https://m.media-amazon.com/images/I/61e0bTrxxsL._SY355_.jpg',
    type: 'Cleanser',
    suitableFor: ['All Skin Types'],
    weatherCompatibility: { hot: true, humid: true },
    keyIngredients: ['Gentle Surfactants'],
    benefits: ['Daily use', 'Non-drying', 'Mild formula'],
    routineType: 'Medical'
  },
  {
    id: 'ast-c-5',
    name: 'The Face Shop Rice Water Bright Cleansing Foam',
    description: 'Brightening cleansing foam with rice water extract.',
    price: 11.99,
    image: 'https://m.media-amazon.com/images/I/414vo0VRW3L._SY355_.jpg',
    type: 'Face Wash',
    suitableFor: ['All Skin Types'],
    weatherCompatibility: { hot: true, humid: true },
    keyIngredients: ['Rice Water', 'Soapwort'],
    benefits: ['Brightening', 'Deep cleansing', 'Natural'],
    routineType: 'Natural'
  },

  // ALL SKIN TYPES - Toners
  {
    id: 'ast-t-1',
    name: 'Klairs Supple Preparation Toner',
    description: 'Hydrating toner that balances and preps skin.',
    price: 19.99,
    image: 'https://m.media-amazon.com/images/I/61K2fOs4y-S._SX466_.jpg',
    type: 'Toner',
    suitableFor: ['All Skin Types'],
    weatherCompatibility: { hot: true, cold: true, dry: true },
    keyIngredients: ['Amino Acids', 'Hyaluronic Acid'],
    benefits: ['Hydration', 'pH balance', 'Prepares skin'],
    routineType: 'Natural'
  },
  {
    id: 'ast-t-2',
    name: 'Thayers Witch Hazel Alcohol-Free Toner',
    description: 'Natural toner that refines pores without drying.',
    price: 10.99,
    image: 'https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcQZ5v34IPxCwb7L5ZnBYT4qpbAa0Xh2bL5tjJGhqHBuOZD_QaZ74I_YBTYrC4SkTvG0OUDvglN4kaVl5bLQ_Risb02Xw9aFNzFv919-OFAoUvhebYxW1HSYRQ',
    type: 'Toner',
    suitableFor: ['All Skin Types'],
    weatherCompatibility: { hot: true, humid: true },
    keyIngredients: ['Witch Hazel', 'Aloe Vera'],
    benefits: ['Pore refining', 'Alcohol-free', 'Natural'],
    routineType: 'Natural'
  },
  {
    id: 'ast-t-3',
    name: 'Isntree Hyaluronic Acid Toner',
    description: 'Multi-molecular hyaluronic acid for deep hydration.',
    price: 16.99,
    image: 'https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcQE-xaMpJ9Li_QwQ0AKxrjsdpiY_JiA7rageyaz6lP086aHT8lwXthao5HNb3hYb3DytYFbxPG7xDYeHM-zjfFi0tdX-ywMXYwaWnUq5sMgF7W8nvjI-oR-XQ',
    type: 'Toner',
    suitableFor: ['All Skin Types'],
    weatherCompatibility: { cold: true, dry: true },
    keyIngredients: ['Hyaluronic Acid'],
    benefits: ['Deep hydration', 'Plumping', 'Multi-layer moisture'],
    routineType: 'Medical'
  },
  {
    id: 'ast-t-4',
    name: 'Pyunkang Yul Essence Toner',
    description: 'Minimalist toner with only essential ingredients.',
    price: 14.99,
    image: 'https://m.media-amazon.com/images/I/51JKh7B+NxL._SX466_.jpg',
    type: 'Toner',
    suitableFor: ['All Skin Types'],
    weatherCompatibility: { hot: true, cold: true, dry: true },
    keyIngredients: ['Barberry Root Extract'],
    benefits: ['Minimalist', 'Balancing', 'Soothing'],
    routineType: 'Natural'
  },
  {
    id: 'ast-t-5',
    name: 'Benton Aloe BHA Skin Toner',
    description: 'Soothing aloe toner with gentle exfoliation.',
    price: 13.99,
    image: 'https://encrypted-tbn0.gstatic.com/shopping?q=tbn:ANd9GcTeeccTpi1YdLz2Sd9ALtn2lsRXt2_A6sZ8w_DPRYJ34CFbo0E4TtSs-rFyVHvFGYocBwg6cgBriREAXTZOwycvYtn2y7yN-6kvNKGZXa_XYxOqXaRzp54crA',
    type: 'Toner',
    suitableFor: ['All Skin Types'],
    weatherCompatibility: { hot: true, humid: true },
    keyIngredients: ['Aloe Vera', 'BHA'],
    benefits: ['Soothing', 'Gentle exfoliation', 'Calming'],
    routineType: 'Natural'
  },

  // ALL SKIN TYPES - Serums
  {
    id: 'ast-s-1',
    name: 'The Ordinary Buffet',
    description: 'Multi-peptide serum for overall skin health.',
    price: 16.99,
    image: 'https://m.media-amazon.com/images/I/510jeHjTlpL._SY355_.jpg',
    type: 'Serum',
    suitableFor: ['All Skin Types'],
    weatherCompatibility: { hot: true, cold: true, dry: true },
    keyIngredients: ['Peptides', 'Amino Acids'],
    benefits: ['Anti-aging', 'Skin health', 'Multi-functional'],
    routineType: 'Medical'
  },
  {
    id: 'ast-s-2',
    name: 'The Ordinary Hyaluronic Acid 2% + B5',
    description: 'Multi-depth hydration with vitamin B5.',
    price: 7.99,
    image: 'https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcTCm6i1GXdIQfb3h5mXU7XHid1wOytfxZdgAVeQGq8EQoYfOe72Xc2KE-cNK3x6BJ9PWHCFhAO_YKUGd4ZdM_nbplEnO4AgE8xVlveyEOFBEwYhoJVBo1W4',
    type: 'Serum',
    suitableFor: ['All Skin Types'],
    weatherCompatibility: { cold: true, dry: true },
    keyIngredients: ['Hyaluronic Acid', 'Vitamin B5'],
    benefits: ['Deep hydration', 'Plumping', 'Surface hydration'],
    routineType: 'Medical'
  },
  {
    id: 'ast-s-3',
    name: 'Vichy Mineral 89',
    description: 'Fortifying and plumping daily booster with volcanic water.',
    price: 29.99,
    image: 'https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcTtqTOsjVnowlrfTZ7MS2RXZ59Vdux36lcPK2XfjdYDjK259E0hY-rSKd2nJbo4VnTrcTplnYd4gIpNnC9uC9hjqrdfZnLpASMsRpqIZd9kwRDYEn-DDiNJiA',
    type: 'Serum',
    suitableFor: ['All Skin Types'],
    weatherCompatibility: { hot: true, cold: true },
    keyIngredients: ['Volcanic Water', 'Hyaluronic Acid'],
    benefits: ['Fortifying', 'Plumping', 'Mineral boost'],
    routineType: 'Medical'
  },
  {
    id: 'ast-s-4',
    name: "Paula's Choice 10% Niacinamide Booster",
    description: 'High-strength niacinamide to visibly improve enlarged pores.',
    price: 44.99,
    image: 'https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcT1cWkQ68Oeqw3ogsc2jy3nSHJ18kkWdjT-joTziBBE4MkiSMoptb9ddsewIyxdP5JrPSJppXGMcjeim-1iI41QJl5Ahm5xovb2XmtEjE3qH3AUJbCHzTrq',
    type: 'Serum',
    suitableFor: ['All Skin Types'],
    weatherCompatibility: { hot: true, humid: true },
    keyIngredients: ['Niacinamide'],
    benefits: ['Pore minimizing', 'Oil control', 'Brightening'],
    routineType: 'Medical'
  },
  {
    id: 'ast-s-5',
    name: 'Olay Regenerist Micro-Sculpting Serum',
    description: 'Advanced anti-aging serum with amino-peptides.',
    price: 32.99,
    image: 'https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcSzfo9u6MD69MVPXd4pAAtEDLoOer-trnBl3PnbsIGUzeljtdvNvXPzT6zxwn12K3vgC70wW7vGu1auKBicrsMxLEF9yQR8vOAKqCakvhtlqq7IonBB2M5n0Q',
    type: 'Serum',
    suitableFor: ['All Skin Types'],
    weatherCompatibility: { cold: true, dry: true },
    keyIngredients: ['Amino-Peptides', 'Vitamin B3'],
    benefits: ['Anti-aging', 'Firming', 'Hydrating'],
    routineType: 'Cosmetic'
  },

  // ALL SKIN TYPES - Sunscreens
  {
    id: 'ast-sun-1',
    name: 'La Roche-Posay Anthelios UVMune Invisible Fluid',
    description: 'Very high broad-spectrum protection with invisible finish.',
    price: 26.99,
    image: 'https://encrypted-tbn0.gstatic.com/shopping?q=tbn:ANd9GcSiBGzBPhWGFMGZIPsZzZ-lpNK4dvgM34ok4rAAMzhe3tX2tj-Ok2l1rGgWmSc6A-x-JrLWq2sGC4o6Z99humptBKLT5nwxXJ-3kNzYFQs8eShmW62TIHhCZA',
    type: 'Sunscreen',
    suitableFor: ['All Skin Types'],
    weatherCompatibility: { hot: true, humid: true },
    keyIngredients: ['UVMune 400', 'Mexoryl'],
    benefits: ['Ultra-high protection', 'Invisible finish', 'Water-resistant'],
    routineType: 'Medical'
  },
  {
    id: 'ast-sun-2',
    name: 'ISDIN Fusion Water',
    description: 'Ultra-light water-based sunscreen.',
    price: 38.99,
    image: 'https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcQ_63HrryZM3heGDpsC3CZINCaQQc9JRkYDSp-Lu9RAJA72qiWJiEnvD6U7kvfT9LqPpvHgckKLdJTeUM8FoaFt-lreblG8Bn3coYtcMk-suyjygnxRJnu6gQ',
    type: 'Sunscreen',
    suitableFor: ['All Skin Types'],
    weatherCompatibility: { hot: true, humid: true },
    keyIngredients: ['Water-based formula'],
    benefits: ['Ultra-light', 'Fast absorption', 'Non-greasy'],
    routineType: 'Medical'
  },
  {
    id: 'ast-sun-3',
    name: 'Bioderma Photoderm Aquafluide',
    description: 'Lightweight fluid texture with high UVA/UVB protection.',
    price: 19.99,
    image: 'https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcRLUettpfUk6IOhvYlNNxoUDsdSMT7ttJWbhGqqmyQBrvL_KE04dQd4Qv6uWICdqaKLx88mKFz3NsSUGchmni52GEgHgGUDOXEcwNEmpBODJ2sjlHSGnWkgyg',
    type: 'Sunscreen',
    suitableFor: ['All Skin Types'],
    weatherCompatibility: { hot: true, humid: true },
    keyIngredients: ['Cellular Bioprotection'],
    benefits: ['Lightweight', 'Non-comedogenic', 'Mat finish'],
    routineType: 'Medical'
  },
  {
    id: 'ast-sun-4',
    name: 'Minimalist 5% Niacinamide + 1% Zinc SPF',
    description: 'Sunscreen with added niacinamide for pore care.',
    price: 12.99,
    image: 'https://m.media-amazon.com/images/I/5166sMOwu5L._SY355_.jpg',
    type: 'Sunscreen',
    suitableFor: ['All Skin Types'],
    weatherCompatibility: { hot: true, humid: true },
    keyIngredients: ['Niacinamide', 'Zinc Oxide'],
    benefits: ['Pore minimizing', 'Oil control', 'Sun protection'],
    routineType: 'Medical'
  },
  {
    id: 'ast-sun-5',
    name: 'Neutrogena Ultra Sheer Dry-Touch',
    description: 'Dry-touch technology for a non-shiny finish.',
    price: 11.99,
    image: 'https://encrypted-tbn0.gstatic.com/shopping?q=tbn:ANd9GcSICLFvEaS_rJ2OYZ5_NO709QTv3bLyFJKTz3QVSHdRZfFPRo3AUKkIuO6N1PP6TUZh-SQL1IwiEvv3QmS4tlTbxoGw4wsRz2g7-G9veFHBd67Ho1owGp2qNEE',
    type: 'Sunscreen',
    suitableFor: ['All Skin Types'],
    weatherCompatibility: { hot: true },
    keyIngredients: ['Helioplex Technology'],
    benefits: ['Dry-touch', 'Non-greasy', 'Fast absorbing'],
    routineType: 'Medical'
  },

  // ALL SKIN TYPES - Night Creams
  {
    id: 'ast-n-1',
    name: 'CeraVe Skin Renewing Night Cream',
    description: 'Peptide complex and hyaluronic acid for overnight renewal.',
    price: 18.99,
    image: 'https://m.media-amazon.com/images/I/71r7bLsvaVL._SY355_.jpg',
    type: 'Night Cream',
    suitableFor: ['All Skin Types'],
    weatherCompatibility: { cold: true, dry: true },
    keyIngredients: ['Peptides', 'Hyaluronic Acid', 'Ceramides'],
    benefits: ['Overnight renewal', 'Barrier repair', 'Anti-aging'],
    routineType: 'Medical'
  },
  {
    id: 'ast-n-2',
    name: 'Clinique Moisture Surge Overnight Mask',
    description: 'Intense hydration mask for overnight moisture boost.',
    price: 39.99,
    image: 'https://sdcdn.io/cl/cl_sku_7NR501_2400x2400_0.jpg?height=700px&width=700px',
    type: 'Night Cream',
    suitableFor: ['All Skin Types'],
    weatherCompatibility: { cold: true, dry: true },
    keyIngredients: ['Hyaluronic Acid', 'Aloe'],
    benefits: ['Intense hydration', 'Cooling', 'Plumping'],
    routineType: 'Cosmetic'
  },
  {
    id: 'ast-n-3',
    name: 'Laneige Water Sleeping Mask',
    description: 'Overnight mask that delivers intense hydration while you sleep.',
    price: 25.99,
    image: 'https://m.media-amazon.com/images/I/41WiRkLH55L._SX466_.jpg',
    type: 'Night Cream',
    suitableFor: ['All Skin Types'],
    weatherCompatibility: { cold: true, dry: true },
    keyIngredients: ['Hydro Ionized Mineral Water', 'Evening Primrose'],
    benefits: ['Overnight hydration', 'Skin purifying', 'Radiance'],
    routineType: 'Cosmetic'
  },
  {
    id: 'ast-n-4',
    name: 'Neutrogena Hydro Boost Night Pressed Serum',
    description: 'Concentrated serum that absorbs quickly for overnight hydration.',
    price: 21.99,
    image: 'https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcQWeWE8lVe9mcypaW5etJFveLrw5y9BJaz0ZsXC-ZkC-jxc1ER9x6Y-PhI2wALpbsC7JT94eSZshGcB0d4t1NOteRV_tpTEwXrO8kB5jceQxVEp5xEFlxzI',
    type: 'Night Cream',
    suitableFor: ['All Skin Types'],
    weatherCompatibility: { dry: true },
    keyIngredients: ['Hyaluronic Acid', 'Olive Extract'],
    benefits: ['Fast absorption', 'Lightweight', 'Hydrating'],
    routineType: 'Medical'
  },
  {
    id: 'ast-n-5',
    name: 'Olay Regenerist Night Recovery Cream',
    description: 'Advanced anti-aging night cream with amino-peptides.',
    price: 28.99,
    image: 'https://m.media-amazon.com/images/I/71zxKzpeabL._SY355_.jpg',
    type: 'Night Cream',
    suitableFor: ['All Skin Types'],
    weatherCompatibility: { cold: true, dry: true },
    keyIngredients: ['Amino-Peptides', 'Vitamin B3'],
    benefits: ['Anti-aging', 'Regenerating', 'Firming'],
    routineType: 'Cosmetic'
  },

  // OILY SKIN - Cleansers
  {
    id: 'os-c-1',
    name: 'La Roche-Posay Effaclar Purifying Foaming Gel',
    description: 'Deep cleansing gel for oily skin with zinc.',
    price: 14.99,
    image: 'https://images.unsplash.com/photo-1556228720-195a672e8a03?w=400&h=400&fit=crop',
    type: 'Cleanser',
    suitableFor: ['Oily Skin'],
    weatherCompatibility: { hot: true, humid: true },
    keyIngredients: ['Zinc Pidolate'],
    benefits: ['Deep cleansing', 'Oil control', 'Purifying'],
    routineType: 'Medical'
  },
  {
    id: 'os-c-2',
    name: 'CeraVe Foaming Facial Cleanser',
    description: 'Foaming cleanser that removes excess oil without stripping.',
    price: 13.99,
    image: 'https://images.unsplash.com/photo-1556228720-195a672e8a03?w=400&h=400&fit=crop',
    type: 'Cleanser',
    suitableFor: ['Oily Skin'],
    weatherCompatibility: { hot: true, humid: true },
    keyIngredients: ['Ceramides', 'Niacinamide', 'Hyaluronic Acid'],
    benefits: ['Oil control', 'Foaming', 'Barrier protection'],
    routineType: 'Medical'
  },
  {
    id: 'os-c-3',
    name: 'Neutrogena Oil-Free Acne Wash',
    description: 'Salicylic acid cleanser for acne-prone oily skin.',
    price: 9.99,
    image: 'https://images.unsplash.com/photo-1556228720-195a672e8a03?w=400&h=400&fit=crop',
    type: 'Face Wash',
    suitableFor: ['Oily Skin', 'Acne-Prone Skin'],
    weatherCompatibility: { hot: true, humid: true },
    keyIngredients: ['Salicylic Acid'],
    benefits: ['Acne fighting', 'Oil-free', 'Deep cleansing'],
    routineType: 'Medical'
  },
  {
    id: 'os-c-4',
    name: 'Gel Cleanser with Salicylic Acid',
    description: 'Gel-based cleanser with BHA for oil control.',
    price: 11.99,
    image: 'https://images.unsplash.com/photo-1556228720-195a672e8a03?w=400&h=400&fit=crop',
    type: 'Cleanser',
    suitableFor: ['Oily Skin'],
    weatherCompatibility: { hot: true, humid: true },
    keyIngredients: ['Salicylic Acid'],
    benefits: ['Gel texture', 'Exfoliating', 'Oil control'],
    routineType: 'Medical'
  },
  {
    id: 'os-c-5',
    name: 'Bioderma Sébium Gel Moussant',
    description: 'Purifying foaming gel for oily combination skin.',
    price: 15.99,
    image: 'https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcQ-rTFwKHFrw_ffXodzygvFH88t8RdVmawh_6PXVXLYinPoCwWJ5f1U5qfz21Ldjy72euBjPSQU4aIkxAz3H_uMH7hiJs2n0eGzXYZ3YHcnsoF-RE2x8W9z',
    type: 'Cleanser',
    suitableFor: ['Oily Skin'],
    weatherCompatibility: { hot: true, humid: true },
    keyIngredients: ['Zinc Sulfate', 'Copper Sulfate'],
    benefits: ['Purifying', 'Soap-free', 'Oil control'],
    routineType: 'Medical'
  },

  // OILY SKIN - Toners
  {
    id: 'os-t-1',
    name: 'Pixi Glow Tonic',
    description: 'Exfoliating toner with 5% glycolic acid.',
    price: 18.99,
    image: 'https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcTkSPmLxneyCSy77jeUKFekoULyu0N5XkmAyRJZCoBaHDMWZ2s0x0ZVVhaeqhZ_hiGlzoSDF5Zc4bY-lplwx8LDTGkClI9DezjSoQD9XOzVvzA9mt2lQPvNfA',
    type: 'Toner',
    suitableFor: ['Oily Skin'],
    weatherCompatibility: { hot: true, humid: true },
    keyIngredients: ['Glycolic Acid', 'Aloe Vera', 'Ginseng'],
    benefits: ['Exfoliating', 'Glow-boosting', 'Pore refining'],
    routineType: 'Medical'
  },
  {
    id: 'os-t-2',
    name: 'Klairs Supple Preparation Toner',
    description: 'Balancing hydrating toner for oily skin.',
    price: 19.99,
    image: 'https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcQN-DKHHfJu3c1mYKajyNTg6BF1rua1Vu8vx8t-UHb42XsUnEq5b4Qs7LUdTzDESXUzK0nveu5KqNQRnqr46F3S2fvwuX5ZfWKcrgvhHIAHAPbmcjWsyG6qtQ',
    type: 'Toner',
    suitableFor: ['Oily Skin'],
    weatherCompatibility: { hot: true, humid: true },
    keyIngredients: ['Amino Acids', 'Hyaluronic Acid'],
    benefits: ['Balancing', 'Hydrating', 'pH adjusting'],
    routineType: 'Natural'
  },
  {
    id: 'os-t-3',
    name: "Paula's Choice Skin Balancing Pore-Reducing Toner",
    description: 'Lightweight toner that minimizes pores.',
    price: 24.99,
    image: 'https://encrypted-tbn0.gstatic.com/shopping?q=tbn:ANd9GcSOvgmSWrEM4_yVrtrff2gvnSpCkkAJMYyMsaqaaLyx2Z518ENdywhXTd22VsqJmsSmdB7N5IwCm474G3UILlIxd_ojM1edwSq79l42UkNh2r8nLaLQppinfQ',
    type: 'Toner',
    suitableFor: ['Oily Skin'],
    weatherCompatibility: { hot: true, humid: true },
    keyIngredients: ['Niacinamide', 'Ceramides'],
    benefits: ['Pore reducing', 'Oil control', 'Balancing'],
    routineType: 'Medical'
  },
  {
    id: 'os-t-4',
    name: 'The Ordinary Glycolic Acid 7% Toning Solution',
    description: 'Exfoliating toner for textured oily skin (use cautiously).',
    price: 8.99,
    image: 'https://images.unsplash.com/photo-1570194065650-d99fb4bedf0a?w=400&h=400&fit=crop',
    type: 'Toner',
    suitableFor: ['Oily Skin'],
    weatherCompatibility: { hot: true },
    keyIngredients: ['Glycolic Acid', 'Amino Acids'],
    benefits: ['Exfoliating', 'Texture improvement', 'Brightening'],
    routineType: 'Medical'
  },
  {
    id: 'os-t-5',
    name: 'Cosrx AHA/BHA Clarifying Treatment Toner',
    description: 'Daily clarifying toner with AHA and BHA.',
    price: 17.99,
    image: 'https://encrypted-tbn0.gstatic.com/shopping?q=tbn:ANd9GcTwR8UJHAJR2BbioOencwLoP6m3m9wfXE_HUjYcPnd_rIcbI-YGwyMx3dQwvAzlOvxJZba0IuHfL5cvqxDnSFYerIXuGd7_X9TjKDfC3Zbet8o-YQo7lwGS',
    type: 'Toner',
    suitableFor: ['Oily Skin'],
    weatherCompatibility: { hot: true, humid: true },
    keyIngredients: ['AHA', 'BHA', 'Mineral Water'],
    benefits: ['Clarifying', 'Exfoliating', 'Purifying'],
    routineType: 'Medical'
  },

  // OILY SKIN - Serums
  {
    id: 'os-s-1',
    name: 'The Ordinary Niacinamide 10% + Zinc 1%',
    description: 'High-strength serum for oil control and pore reduction.',
    price: 6.99,
    image: 'https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcQ-AhpkxkGO7PuLpB5JvAPkP2khNnaD3W5JvbisubYI6g9FbF2fUUG8zcQexeRwG5Jd9cl0p3mep7G8oNrQzuQEKeNpQ64g5KxxvyuVcFSbCjud1EwyLiQ9LQ',
    type: 'Serum',
    suitableFor: ['Oily Skin'],
    weatherCompatibility: { hot: true, humid: true },
    keyIngredients: ['Niacinamide', 'Zinc'],
    benefits: ['Oil control', 'Pore minimizing', 'Blemish reduction'],
    routineType: 'Medical'
  },
  {
    id: 'os-s-2',
    name: 'La Roche-Posay Effaclar Serum',
    description: 'Triple-acid serum for oily acne-prone skin.',
    price: 39.99,
    image: 'https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcQOheDLmFflYwPprsLVMBOaUhM2ggZ4XyRk4-AzpOx04x0yxlPXOX4soGy6uQlMLI_p2XNsHbPGTCsOvUZmngq6yJDoEhkf6mtszXDJLK9TI5r133Dsi6E8',
    type: 'Serum',
    suitableFor: ['Oily Skin', 'Acne-Prone Skin'],
    weatherCompatibility: { hot: true, humid: true },
    keyIngredients: ['Salicylic Acid', 'Glycolic Acid', 'Niacinamide'],
    benefits: ['Triple acid', 'Oil control', 'Anti-acne'],
    routineType: 'Medical'
  },
  {
    id: 'os-s-3',
    name: 'The Inkey List Salicylic Acid Serum',
    description: 'BHA serum for clearing pores and reducing breakouts.',
    price: 9.99,
    image: 'https://m.media-amazon.com/images/I/5101c3q-3lL._SY355_.jpg',
    type: 'Serum',
    suitableFor: ['Oily Skin', 'Acne-Prone Skin'],
    weatherCompatibility: { hot: true, humid: true },
    keyIngredients: ['Salicylic Acid', 'Zinc'],
    benefits: ['Pore clearing', 'Breakout reduction', 'Oil control'],
    routineType: 'Medical'
  },
  {
    id: 'os-s-4',
    name: 'Cosrx BHA Blackhead Power Liquid',
    description: 'Gentle BHA liquid for blackheads and sebum control.',
    price: 19.99,
    image: 'https://m.media-amazon.com/images/I/51v4BYYZfiL._SX466_.jpg',
    type: 'Serum',
    suitableFor: ['Oily Skin'],
    weatherCompatibility: { hot: true, humid: true },
    keyIngredients: ['BHA', 'Willow Bark Water'],
    benefits: ['Blackhead removal', 'Sebum control', 'Gentle exfoliation'],
    routineType: 'Medical'
  },
  {
    id: 'os-s-5',
    name: 'Drunk Elephant T.L.C. Framboos',
    description: 'AHA/BHA night serum for resurfacing.',
    price: 90.99,
    image: 'https://images-cdn.ubuy.co.in/67ec9b97c85698ef5f0664a2-drunk-elephant-t-l-c-framboos-glycolic.jpg',
    type: 'Serum',
    suitableFor: ['Oily Skin'],
    weatherCompatibility: { hot: true },
    keyIngredients: ['Glycolic Acid', 'Lactic Acid', 'Salicylic Acid'],
    benefits: ['Resurfacing', 'Texture improvement', 'Brightening'],
    routineType: 'Medical'
  },

  // OILY SKIN - Sunscreens
  {
    id: 'os-sun-1',
    name: 'Foxtale Sunscreen',
    description: 'Lightweight sunscreen for oily skin.',
    price: 14.99,
    image: 'https://images.unsplash.com/photo-1559757148-5c350d0d3c56?w=400&h=400&fit=crop',
    type: 'Sunscreen',
    suitableFor: ['Oily Skin'],
    weatherCompatibility: { hot: true, humid: true },
    keyIngredients: ['Broad Spectrum Filters'],
    benefits: ['Lightweight', 'Non-greasy', 'Matte finish'],
    routineType: 'Cosmetic'
  },
  {
    id: 'os-sun-2',
    name: 'Wishcare Sunscreen',
    description: 'Oil-control sunscreen with matte finish.',
    price: 13.99,
    image: 'https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcRoW7iyLN703wfVn9lFBbmeL7hUoqfCZlmRNxPTLgbvDyKihCOvSGOzbPEAsLnel_HEg3jAdwzO2d53m68YU6PeyqR4ajQgZ_BZqB9tDG7yVQOsVP8a6DoQcMo',
    type: 'Sunscreen',
    suitableFor: ['Oily Skin'],
    weatherCompatibility: { hot: true, humid: true },
    keyIngredients: ['Mattifying Agents'],
    benefits: ['Oil control', 'Matte finish', 'Non-comedogenic'],
    routineType: 'Cosmetic'
  },
  {
    id: 'os-sun-3',
    name: 'Minimalist Sunscreen',
    description: 'Multi-vitamin sunscreen for oily skin.',
    price: 12.99,
    image: 'https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcS-TAUV_3oaRPLfaA9XU2ie6bDm_EQxgJ5M86bdLk-Zqgy9UGymNOTeGSDXhi8kg57Bc8uDyc3q8wmgT6oabSjVdlZm5laYgLRyy7y-6B3dMXZAgzqmwuc',
    type: 'Sunscreen',
    suitableFor: ['Oily Skin'],
    weatherCompatibility: { hot: true, humid: true },
    keyIngredients: ['Multi-Vitamins'],
    benefits: ['Lightweight', 'Multi-vitamin', 'Non-greasy'],
    routineType: 'Medical'
  },
  {
    id: 'os-sun-4',
    name: 'Aqualogica Sunscreen',
    description: 'Hydrating yet oil-free sunscreen.',
    price: 15.99,
    image: 'https://encrypted-tbn0.gstatic.com/shopping?q=tbn:ANd9GcSug86x_WruQSGqvq1DlUFseRAi83U4AGcUdgy4QU3VL40qYRbmREzCSD3jcKR2-ZXei7HEmYfmsRguDG-zG7e7PKM4MTHF9y1FCBiS_3JNSW4I6604-x0IcfT4',
    type: 'Sunscreen',
    suitableFor: ['Oily Skin'],
    weatherCompatibility: { hot: true, humid: true },
    keyIngredients: ['Hyaluronic Acid'],
    benefits: ['Oil-free', 'Hydrating', 'Lightweight'],
    routineType: 'Cosmetic'
  },
  {
    id: 'os-sun-5',
    name: 'Cetaphil Sunscreen',
    description: 'Dermatologist-recommended sunscreen for oily skin.',
    price: 16.99,
    image: 'https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcThHs2zn712Q-jGLTWj7sg1Ns80wl7meLnDXu1RY0b8YFlcbd6mdCTPRjQveniNiw-staOeOvEBgOI4ulkgKKHyCSUm2UWMxfOdzXNhq3LdOUt_UmZApLos',
    type: 'Sunscreen',
    suitableFor: ['Oily Skin'],
    weatherCompatibility: { hot: true, humid: true },
    keyIngredients: ['Broad Spectrum'],
    benefits: ['Dermatologist-recommended', 'Oil-control', 'Non-comedogenic'],
    routineType: 'Medical'
  },

  // OILY SKIN - Night Creams
  {
    id: 'os-n-1',
    name: 'Neutrogena Hydro Boost Water Gel',
    description: 'Oil-free gel for lightweight overnight hydration.',
    price: 18.99,
    image: 'https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcQDqmASvn64zv-wEkUUikAuvFoz425cQbSKiOik3i6DZfE-xqAx-HpzxvbUT8SnEWWSaI82RNSt_CbEeZnrYUCiZ_ineT9CP4HmcbW_LVF3o3dkER5XeUmhzl-XlsaqTHVq1_guKQ&usqp=CAc',
    type: 'Night Cream',
    suitableFor: ['Oily Skin'],
    weatherCompatibility: { hot: true, humid: true },
    keyIngredients: ['Hyaluronic Acid'],
    benefits: ['Oil-free', 'Gel texture', 'Lightweight'],
    routineType: 'Medical'
  },
  {
    id: 'os-n-2',
    name: 'La Roche-Posay Effaclar Duo (+)',
    description: 'Dual-action moisturizer for acne-prone oily skin.',
    price: 22.99,
    image: 'https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcT3Z1Zu8dl8fYevL0yD5s_MqXZhtKxPBggmBIgYPAryK8ACYBL9aNY4ILkBpZrQ6eeSwln7PMjlyw44dVhFDz67Umr7H8nXy57_qVYqCVxZPwoTINeg2pPueg',
    type: 'Night Cream',
    suitableFor: ['Oily Skin', 'Acne-Prone Skin'],
    weatherCompatibility: { hot: true, humid: true },
    keyIngredients: ['Niacinamide', 'LHA', 'Procerad'],
    benefits: ['Anti-acne', 'Oil control', 'Dual action'],
    routineType: 'Medical'
  },
  {
    id: 'os-n-3',
    name: 'CeraVe PM Facial Moisturizing Lotion',
    description: 'Lightweight PM lotion for oily skin.',
    price: 16.99,
    image: 'https://m.media-amazon.com/images/I/61NsunzEV8L._SY355_.jpg',
    type: 'Night Cream',
    suitableFor: ['Oily Skin'],
    weatherCompatibility: { hot: true, humid: true },
    keyIngredients: ['Niacinamide', 'Ceramides', 'Hyaluronic Acid'],
    benefits: ['Lightweight', 'Brightening', 'Barrier repair'],
    routineType: 'Medical'
  },
  {
    id: 'os-n-4',
    name: 'Benton Snail Bee High Content Cream',
    description: 'Lightweight cream with snail mucin and bee venom.',
    price: 19.99,
    image: 'https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcQweVoVWUQZCxRQ9gCm9ChKlHfgNAjhLckawYNPHm4beclr42yD5vnjEXarOwzyXhOBtoJXPZwycphV40a0GkEm-Vyh1EXgtYuxNC6GZ1D6x7tZLAKlJZMOOg',
    type: 'Night Cream',
    suitableFor: ['Oily Skin'],
    weatherCompatibility: { hot: true, humid: true },
    keyIngredients: ['Snail Mucin', 'Bee Venom'],
    benefits: ['Healing', 'Lightweight', 'Soothing'],
    routineType: 'Natural'
  },
  {
    id: 'os-n-5',
    name: 'Light Gel-Cream with Retinol',
    description: 'Lightweight retinol cream for oily skin (if tolerated).',
    price: 24.99,
    image: 'https://images.unsplash.com/photo-1556228720-195a672e8a03?w=400&h=400&fit=crop',
    type: 'Night Cream',
    suitableFor: ['Oily Skin'],
    weatherCompatibility: { hot: true },
    keyIngredients: ['Retinol'],
    benefits: ['Anti-aging', 'Gel texture', 'Oil control'],
    routineType: 'Medical'
  },

  // SENSITIVE SKIN - Moisturizers
  {
    id: 'ss-m-1',
    name: 'Vanicream Moisturizing Cream',
    description: 'Fragrance-free cream for very sensitive skin.',
    price: 16.99,
    image: 'https://m.media-amazon.com/images/I/519CiSGjEvL._AC_UL480_FMwebp_QL65_.jpg',
    type: 'Moisturizer',
    suitableFor: ['Sensitive Skin'],
    weatherCompatibility: { cold: true, dry: true },
    keyIngredients: ['Petrolatum', 'Sorbitol'],
    benefits: ['Fragrance-free', 'Gentle', 'Barrier repair'],
    routineType: 'Medical'
  },
  {
    id: 'ss-m-2',
    name: 'La Roche-Posay Toleriane Double Repair',
    description: 'Prebiotic moisturizer for sensitive skin.',
    price: 19.99,
    image: 'https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcRLPdj6FJ7GUCQiGKCBwoB2EUEusKcEZbPQYFbQlHzLVouFGEqq1uEtIFHdjJ8PnlGMOr6dbVwct9Qj0pbXk9px2ygHq3ZAnBFuz-EwanBPSaXzp7AqMIe9OQ',
    type: 'Moisturizer',
    suitableFor: ['Sensitive Skin'],
    weatherCompatibility: { cold: true, dry: true },
    keyIngredients: ['Ceramides', 'Niacinamide', 'Thermal Water'],
    benefits: ['Prebiotic', 'Calming', 'Barrier repair'],
    routineType: 'Medical'
  },
  {
    id: 'ss-m-3',
    name: 'CeraVe Moisturizing Cream',
    description: 'Fragrance-free rich cream with essential ceramides.',
    price: 15.99,
    image: 'https://m.media-amazon.com/images/I/61zO5gx-PHL._AC_SX416_CB1169409_QL70_.jpg',
    type: 'Moisturizer',
    suitableFor: ['Sensitive Skin'],
    weatherCompatibility: { cold: true, dry: true },
    keyIngredients: ['Ceramides', 'Hyaluronic Acid'],
    benefits: ['Fragrance-free', 'Rich hydration', 'Barrier protection'],
    routineType: 'Medical'
  },
  {
    id: 'ss-m-4',
    name: 'Avene Tolerance Extreme',
    description: 'Minimalist formula for extremely sensitive skin.',
    price: 28.99,
    image: 'https://m.media-amazon.com/images/I/61GranTHFlL._SL1500_.jpg',
    type: 'Moisturizer',
    suitableFor: ['Sensitive Skin'],
    weatherCompatibility: { cold: true, dry: true },
    keyIngredients: ['Thermal Water', 'Squalane'],
    benefits: ['Minimalist', 'Sterile formula', 'Ultra-calming'],
    routineType: 'Medical'
  },
  {
    id: 'ss-m-5',
    name: 'First Aid Beauty Ultra Repair Cream',
    description: 'Intensive repair cream with colloidal oatmeal.',
    price: 34.99,
    image: 'https://encrypted-tbn0.gstatic.com/shopping?q=tbn:ANd9GcRmde5VKZF7TMq1ZptlSaUAkiGbeh2kztpuaerN2Vfg-q8VIEiwP2OISL7MhkodrKhG569O8LCiZ85KXfUtSC85PusmOfShahjN6bcj6bY_XF-CyCLcU6EwNQ',
    type: 'Moisturizer',
    suitableFor: ['Sensitive Skin'],
    weatherCompatibility: { cold: true, dry: true },
    keyIngredients: ['Colloidal Oatmeal', 'Shea Butter', 'Ceramides'],
    benefits: ['Intensive repair', 'Soothing', 'Barrier support'],
    routineType: 'Medical'
  },

  // SENSITIVE SKIN - Cleansers
  {
    id: 'ss-c-1',
    name: 'Cetaphil Gentle Skin Cleanser',
    description: 'Classic gentle cleanser for sensitive skin.',
    price: 12.99,
    image: 'https://m.media-amazon.com/images/I/51ldoDeRrcL._AC_SX416_CB1169409_QL70_.jpg',
    type: 'Cleanser',
    suitableFor: ['Sensitive Skin'],
    weatherCompatibility: { hot: true, cold: true, dry: true },
    keyIngredients: ['Glycerin'],
    benefits: ['Ultra-gentle', 'Fragrance-free', 'Non-irritating'],
    routineType: 'Medical'
  },
  {
    id: 'ss-c-2',
    name: 'La Roche-Posay Toleriane Dermo Cleanser',
    description: 'Gentle milk cleanser for sensitive skin.',
    price: 15.99,
    image: 'https://m.media-amazon.com/images/I/31nn1Qqb1CL._SY300_SX300_QL70_FMwebp_.jpg',
    type: 'Cleanser',
    suitableFor: ['Sensitive Skin'],
    weatherCompatibility: { cold: true, dry: true },
    keyIngredients: ['Thermal Water', 'Glycerin'],
    benefits: ['Milk texture', 'Soothing', 'No rinse option'],
    routineType: 'Medical'
  },
  {
    id: 'ss-c-3',
    name: 'Bioderma Sensibio H2O',
    description: 'Micellar water for sensitive skin cleansing.',
    price: 14.99,
    image: 'https://encrypted-tbn0.gstatic.com/shopping?q=tbn:ANd9GcRQixPzgo5laSNiRytsWrVNFlkuKt4mLLw5uexKFigoGXrHj4-zw8UD_O79W1bZ8XayvrkYAKMGTkcs6iw6GJ3PpO2bup_qjg',
    type: 'Cleanser',
    suitableFor: ['Sensitive Skin'],
    weatherCompatibility: { hot: true, cold: true },
    keyIngredients: ['Micelles', 'Cucumber Extract'],
    benefits: ['No rinse', 'Gentle', 'Micellar technology'],
    routineType: 'Medical'
  },
  {
    id: 'ss-c-4',
    name: 'Simple Soothing Facial Wash',
    description: 'No harsh chemicals facial wash for sensitive skin.',
    price: 8.99,
    image: 'https://encrypted-tbn0.gstatic.com/shopping?q=tbn:ANd9GcQ2JXZMy5zFMSg6rJuT-XBUOCh3B2MvC2ZcZBt2AgZEnRfsk1m2ofsofd7lBgJ_SbyNeVZCC1c1VwEFh02GHi1P4IEcHyF2kvMqrvOScEZz1qIfvgVlst3gvA',
    type: 'Face Wash',
    suitableFor: ['Sensitive Skin'],
    weatherCompatibility: { hot: true, cold: true },
    keyIngredients: ['Vitamin E', 'Pro-Vitamin B5'],
    benefits: ['No harsh chemicals', 'Soothing', 'Gentle'],
    routineType: 'Natural'
  },
  {
    id: 'ss-c-5',
    name: 'Klairs Rich Moist Foaming Cleanser',
    description: 'Hypoallergenic foaming cleanser for sensitive skin.',
    price: 15.99,
    image: 'https://m.media-amazon.com/images/I/61Qwyv1vphL._SX466_.jpg',
    type: 'Cleanser',
    suitableFor: ['Sensitive Skin'],
    weatherCompatibility: { hot: true, cold: true },
    keyIngredients: ['Amino Acids', 'Hyaluronic Acid'],
    benefits: ['Hypoallergenic', 'Rich foam', 'pH balanced'],
    routineType: 'Natural'
  },

  // SENSITIVE SKIN - Toners
  {
    id: 'ss-t-1',
    name: 'Klairs Supple Preparation Facial Toner (Unscented)',
    description: 'Unscented version for sensitive skin.',
    price: 19.99,
    image: 'https://encrypted-tbn0.gstatic.com/shopping?q=tbn:ANd9GcRumK9WpsxigSkfbkIBre3206vVjEM9-3IUhDvgUxmPdK_hT44Qv8chVCodJLapUiovZO733m4pYRfusJ_BRpQVKVL9PKGqwTDBi6A-T-H7s9xRZXqrJyYFgg',
    type: 'Toner',
    suitableFor: ['Sensitive Skin'],
    weatherCompatibility: { hot: true, cold: true, dry: true },
    keyIngredients: ['Amino Acids', 'Hyaluronic Acid'],
    benefits: ['Unscented', 'Hydrating', 'Soothing'],
    routineType: 'Natural'
  },
  {
    id: 'ss-t-2',
    name: 'Avene Hydrance Intense Rehydrating Serum',
    description: 'Soothing hydrating serum that can work as toner.',
    price: 32.99,
    image: 'https://incidecoder-content.storage.googleapis.com/bb8cf77a-b5a7-483d-847e-b9c5f3f4b5fb/products/avene-hydrance-intense-rehydrating-serum/avene-hydrance-intense-rehydrating-serum_front_photo_300x300@2x.webp',
    type: 'Toner',
    suitableFor: ['Sensitive Skin'],
    weatherCompatibility: { cold: true, dry: true },
    keyIngredients: ['Thermal Water', 'Hyaluronic Acid'],
    benefits: ['Soothing', 'Intense hydration', 'Calming'],
    routineType: 'Medical'
  },
  {
    id: 'ss-t-3',
    name: 'Isntree Hyaluronic Acid Toner',
    description: 'Gentle hyaluronic acid toner for sensitive skin.',
    price: 16.99,
    image: 'https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcQE-xaMpJ9Li_QwQ0AKxrjsdpiY_JiA7rageyaz6lP086aHT8lwXthao5HNb3hYb3DytYFbxPG7xDYeHM-zjfFi0tdX-ywMXYwaWnUq5sMgF7W8nvjI-oR-XQ',
    type: 'Toner',
    suitableFor: ['Sensitive Skin'],
    weatherCompatibility: { cold: true, dry: true },
    keyIngredients: ['Hyaluronic Acid'],
    benefits: ['Gentle', 'Hydrating', 'Multi-layer moisture'],
    routineType: 'Medical'
  },
  {
    id: 'ss-t-4',
    name: 'Pyunkang Yul Essence Toner',
    description: 'Minimalist essence toner for sensitive skin.',
    price: 14.99,
    image: 'https://m.media-amazon.com/images/I/51JKh7B+NxL._SX466_.jpg',
    type: 'Toner',
    suitableFor: ['Sensitive Skin'],
    weatherCompatibility: { hot: true, cold: true, dry: true },
    keyIngredients: ['Barberry Root Extract'],
    benefits: ['Minimalist', 'Calming', 'Balancing'],
    routineType: 'Natural'
  },
  {
    id: 'ss-t-5',
    name: 'Benton Aloe BHA Skin Toner',
    description: 'Soothing aloe toner with gentle BHA.',
    price: 13.99,
    image: 'https://encrypted-tbn0.gstatic.com/shopping?q=tbn:ANd9GcTeeccTpi1YdLz2Sd9ALtn2lsRXt2_A6sZ8w_DPRYJ34CFbo0E4TtSs-rFyVHvFGYocBwg6cgBriREAXTZOwycvYtn2y7yN-6kvNKGZXa_XYxOqXaRzp54crA',
    type: 'Toner',
    suitableFor: ['Sensitive Skin'],
    weatherCompatibility: { hot: true, humid: true },
    keyIngredients: ['Aloe Vera', 'BHA'],
    benefits: ['Soothing', 'Gentle exfoliation', 'Calming'],
    routineType: 'Natural'
  },

  // SENSITIVE SKIN - Serums
  {
    id: 'ss-s-1',
    name: "Paula's Choice Calm Redness Relief Serum",
    description: 'Calming serum for sensitive, reactive skin.',
    price: 38.99,
    image: 'https://m.media-amazon.com/images/I/61IEJcskKxL._SL1500_.jpg',
    type: 'Serum',
    suitableFor: ['Sensitive Skin'],
    weatherCompatibility: { cold: true, dry: true },
    keyIngredients: ['Ceramides', 'Allantoin', 'Licorice Extract'],
    benefits: ['Redness relief', 'Calming', 'Barrier repair'],
    routineType: 'Medical'
  },
  {
    id: 'ss-s-2',
    name: 'The Ordinary Buffet',
    description: 'Multi-peptide serum gentle enough for sensitive skin.',
    price: 16.99,
    image: 'https://m.media-amazon.com/images/I/510jeHjTlpL._SY355_.jpg',
    type: 'Serum',
    suitableFor: ['Sensitive Skin'],
    weatherCompatibility: { hot: true, cold: true },
    keyIngredients: ['Peptides', 'Amino Acids'],
    benefits: ['Multi-functional', 'Gentle', 'Anti-aging'],
    routineType: 'Medical'
  },
  {
    id: 'ss-s-3',
    name: 'La Roche-Posay Cicaplast B5 Serum',
    description: 'Repairing serum with madecassoside for sensitive skin.',
    price: 29.99,
    image: 'https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcQ_GUx_5rnBg-EpDtkg-ST5vLMqdVl2el6Z1M7nAh9iFVOQ07oE0D5PZlCuYkYljOaBbbamjPX0t5KCKGc44SyPBrpFujst5yu3cqu-WLykd0Fhqb1-cg8',
    type: 'Serum',
    suitableFor: ['Sensitive Skin'],
    weatherCompatibility: { cold: true, dry: true },
    keyIngredients: ['Madecassoside', 'Panthenol', 'Vitamin B5'],
    benefits: ['Repairing', 'Soothing', 'Anti-irritation'],
    routineType: 'Medical'
  },
  {
    id: 'ss-s-4',
    name: 'Avène Hydrance Intense Rehydrating Serum',
    description: 'Intense hydrating serum with thermal water.',
    price: 32.99,
    image: 'https://m.media-amazon.com/images/I/71LOMl5OMsL._SL1500_.jpg',
    type: 'Serum',
    suitableFor: ['Sensitive Skin'],
    weatherCompatibility: { cold: true, dry: true },
    keyIngredients: ['Thermal Water', 'Hyaluronic Acid'],
    benefits: ['Intense hydration', 'Soothing', 'Calming'],
    routineType: 'Medical'
  },
  {
    id: 'ss-s-5',
    name: 'Dr. Jart+ Cicapair Tiger Grass Serum',
    description: 'Centella-based serum for calming sensitive skin.',
    price: 48.99,
    image: 'https://m.media-amazon.com/images/I/61XVzFMC8yL._SY355_.jpg',
    type: 'Serum',
    suitableFor: ['Sensitive Skin'],
    weatherCompatibility: { cold: true, dry: true },
    keyIngredients: ['Centella Asiatica', 'Niacinamide'],
    benefits: ['Calming', 'Redness reduction', 'Strengthening'],
    routineType: 'Medical'
  },

  // SENSITIVE SKIN - Sunscreens
  {
    id: 'ss-sun-1',
    name: 'La Roche-Posay Anthelios Ultra SPF',
    description: 'Very high protection for sensitive skin.',
    price: 26.99,
    image: 'https://encrypted-tbn0.gstatic.com/shopping?q=tbn:ANd9GcSiBGzBPhWGFMGZIPsZzZ-lpNK4dvgM34ok4rAAMzhe3tX2tj-Ok2l1rGgWmSc6A-x-JrLWq2sGC4o6Z99humptBKLT5nwxXJ-3kNzYFQs8eShmW62TIHhCZA',
    type: 'Sunscreen',
    suitableFor: ['Sensitive Skin'],
    weatherCompatibility: { hot: true },
    keyIngredients: ['UVMune 400', 'Thermal Water'],
    benefits: ['Very high protection', 'Invisible finish', 'Tested on sensitive skin'],
    routineType: 'Medical'
  },
  {
    id: 'ss-sun-2',
    name: 'Bioderma Photoderm Sensitive Skin',
    description: 'Cellular protection for sensitive skin.',
    price: 22.99,
    image: 'https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcQE2MSNGdBIyUcqmN-_2nXU-2jZC7-5RwGbckCbdyozzMthQetsftRgNpuZOPoFKQaRoJ-OuUBxWk3pwm0bt67oskkBp8aQgTA4dGlT5aoHDKDyUdNg8aMC',
    type: 'Sunscreen',
    suitableFor: ['Sensitive Skin'],
    weatherCompatibility: { hot: true },
    keyIngredients: ['Cellular Bioprotection'],
    benefits: ['Gentle', 'Non-comedogenic', 'High tolerance'],
    routineType: 'Medical'
  },
  {
    id: 'ss-sun-3',
    name: 'ISDIN Eryfotona Actinica',
    description: 'Mineral sunscreen with DNA repair enzymes.',
    price: 55.99,
    image: 'https://m.media-amazon.com/images/I/41TLgyNO91L._SY355_.jpg',
    type: 'Sunscreen',
    suitableFor: ['Sensitive Skin'],
    weatherCompatibility: { hot: true },
    keyIngredients: ['Zinc Oxide', 'DNA Repair Enzymes'],
    benefits: ['Mineral protection', 'DNA repair', 'Ultra-gentle'],
    routineType: 'Medical'
  },
  {
    id: 'ss-sun-4',
    name: 'Avene Very High Protection Emulsion',
    description: 'Ultra-gentle emulsion for sensitive skin.',
    price: 29.99,
    image: 'https://encrypted-tbn0.gstatic.com/shopping?q=tbn:ANd9GcThdZev4mDgPMWq_sBMKlBMgMlrEA-hAV2P_NJ5y6ysVeB_UIBkKutPN1gpMKCI5L4eLKCeg3zwv4Vs0FLCi6HJXtH_rK8',
    type: 'Sunscreen',
    suitableFor: ['Sensitive Skin'],
    weatherCompatibility: { hot: true },
    keyIngredients: ['Thermal Water', 'Pre-Tocopheryl'],
    benefits: ['Very high protection', 'Soothing', 'Photostable'],
    routineType: 'Medical'
  },
  {
    id: 'ss-sun-5',
    name: 'Neutrogena Sheer Zinc',
    description: 'Mineral zinc sunscreen for sensitive skin.',
    price: 13.99,
    image: 'https://encrypted-tbn0.gstatic.com/shopping?q=tbn:ANd9GcT9fMHH2Jbu6ohAOXwc09ju33adGQiqwX9XLzh9EcLEHeyS78_aC7M3kETnWTyocx0RK6VRExSCWN-LdgyzTluzsbvpk28Y7Edb1qf4ofyDQh8cAyul_0x9Lw',
    type: 'Sunscreen',
    suitableFor: ['Sensitive Skin'],
    weatherCompatibility: { hot: true },
    keyIngredients: ['Zinc Oxide'],
    benefits: ['Mineral', 'Gentle', 'Broad spectrum'],
    routineType: 'Medical'
  },

  // SENSITIVE SKIN - Night Creams
  {
    id: 'ss-n-1',
    name: 'CeraVe Skin Renewing Night Cream',
    description: 'Gentle night cream with peptides for sensitive skin.',
    price: 18.99,
    image: 'https://m.media-amazon.com/images/I/71r7bLsvaVL._SY355_.jpg',
    type: 'Night Cream',
    suitableFor: ['Sensitive Skin'],
    weatherCompatibility: { cold: true, dry: true },
    keyIngredients: ['Peptides', 'Ceramides', 'Hyaluronic Acid'],
    benefits: ['Gentle', 'Overnight renewal', 'Barrier repair'],
    routineType: 'Medical'
  },
  {
    id: 'ss-n-2',
    name: 'First Aid Beauty Ultra Repair Cream',
    description: 'Multi-purpose repair cream for overnight use.',
    price: 34.99,
    image: 'https://encrypted-tbn0.gstatic.com/shopping?q=tbn:ANd9GcRmde5VKZF7TMq1ZptlSaUAkiGbeh2kztpuaerN2Vfg-q8VIEiwP2OISL7MhkodrKhG569O8LCiZ85KXfUtSC85PusmOfShahjN6bcj6bY_XF-CyCLcU6EwNQ',
    type: 'Night Cream',
    suitableFor: ['Sensitive Skin'],
    weatherCompatibility: { cold: true, dry: true },
    keyIngredients: ['Colloidal Oatmeal', 'Shea Butter'],
    benefits: ['Intensive repair', 'Soothing', 'Multi-purpose'],
    routineType: 'Medical'
  },
  {
    id: 'ss-n-3',
    name: 'Avene Tolerance Extreme Emulsion',
    description: 'Sterile minimalist night emulsion.',
    price: 32.99,
    image: 'https://d1iuscsovtvj4y.cloudfront.net/__sized__/products/42552_00-thumbnail-1080x1080-70.jpg',
    type: 'Night Cream',
    suitableFor: ['Sensitive Skin'],
    weatherCompatibility: { cold: true, dry: true },
    keyIngredients: ['Thermal Water', 'Squalane'],
    benefits: ['Sterile formula', 'Minimalist', 'Ultra-calming'],
    routineType: 'Medical'
  },
  {
    id: 'ss-n-4',
    name: 'Dr. Jart+ Cicapair Tiger Grass Sleeping Mask',
    description: 'Overnight centella mask for sensitive skin.',
    price: 42.99,
    image: 'https://images-static.nykaa.com/media/catalog/product/0/d/0dc11d08809724476168_1.png?tr=w-344,h-344,cm-pad_resize',
    type: 'Night Cream',
    suitableFor: ['Sensitive Skin'],
    weatherCompatibility: { cold: true, dry: true },
    keyIngredients: ['Centella Asiatica', 'Niacinamide'],
    benefits: ['Calming', 'Overnight treatment', 'Redness reduction'],
    routineType: 'Medical'
  },
  {
    id: 'ss-n-5',
    name: "Paula's Choice Calm Repairing Moisturizer",
    description: 'Fragrance-free night moisturizer for reactive skin.',
    price: 36.99,
    image: 'https://m.media-amazon.com/images/I/61UyxT1wuNL._SY355_.jpg',
    type: 'Night Cream',
    suitableFor: ['Sensitive Skin'],
    weatherCompatibility: { cold: true, dry: true },
    keyIngredients: ['Ceramides', 'Niacinamide', 'Licorice Extract'],
    benefits: ['Fragrance-free', 'Calming', 'Barrier repair'],
    routineType: 'Medical'
  },

  // COMBINATION SKIN - Moisturizers
  {
    id: 'cs-m-1',
    name: 'Neutrogena Hydro Boost Water Gel',
    description: 'Oil-free gel cream perfect for combination skin hydration.',
    price: 18.99,
    image: 'https://m.media-amazon.com/images/I/41zlBkFoxQL._AC_SR250,250_QL65_.jpg',
    type: 'Moisturizer',
    suitableFor: ['Combination Skin'],
    weatherCompatibility: { hot: true, humid: true },
    keyIngredients: ['Hyaluronic Acid'],
    benefits: ['Oil-free', 'Lightweight', 'Non-greasy'],
    routineType: 'Medical'
  },
  {
    id: 'cs-m-2',
    name: 'Clinique Dramatically Different Moisturizing Gel',
    description: 'Lightweight gel-cream moisturizer for combination skin.',
    price: 29.99,
    image: 'https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcRGWermW734_5XMljywrW3D0AzYN5x7qSWX4BmE8Io0trTdu3-HAJ3WWZflLu1nEwwmMT8nzpxs1J3vD8MiL8lkDB3WsZFrXzPrWAITIuzRil8kwzSOZoulhzF-AsHFklBcebRoy23YcA&usqp=CAc',
    type: 'Moisturizer',
    suitableFor: ['Combination Skin'],
    weatherCompatibility: { hot: true, humid: true },
    keyIngredients: ['Hyaluronic Acid', 'Glycerin'],
    benefits: ['Balancing', 'Lightweight', 'Fast absorbing'],
    routineType: 'Cosmetic'
  },
  {
    id: 'cs-m-3',
    name: 'Glossier Priming Moisturizer',
    description: 'Universal daily moisturizer that primes and hydrates.',
    price: 25.99,
    image: 'https://glossier-prod.imgix.net/products/glossier-priming-moisturizer-carousel-03.png?auto=compress,format&cs=srgb&w=916',
    type: 'Moisturizer',
    suitableFor: ['Combination Skin'],
    weatherCompatibility: { hot: true, cold: true },
    keyIngredients: ['Red Algae', 'Glycerin'],
    benefits: ['Priming', 'Universal', 'Smooth finish'],
    routineType: 'Cosmetic'
  },
  {
    id: 'cs-m-4',
    name: 'Cosrx Oil-Free Ultra-Moisturizing Lotion',
    description: 'Lightweight lotion with birch sap for balanced hydration.',
    price: 16.99,
    image: 'https://wsrv.nl/?url=https%3A%2F%2Fbb-asset.blr1.cdn.digitaloceanspaces.com%2Fassets%2F2025%2F9%2Fl1ogubqe9gd&width=1080&quality=100&v=9&height=500&output=webp',
    type: 'Moisturizer',
    suitableFor: ['Combination Skin'],
    weatherCompatibility: { hot: true, humid: true },
    keyIngredients: ['Birch Sap', 'Hyaluronic Acid'],
    benefits: ['Oil-free', 'Balancing', 'Lightweight'],
    routineType: 'Natural'
  },
  {
    id: 'cs-m-5',
    name: 'Belif The True Cream Aqua Bomb',
    description: 'Refreshing gel-cream that provides instant burst of hydration.',
    price: 38.99,
    image: 'https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcTyTl8q2gpqksC8oWNFx89lKliFQ4ldD2nU1icvL-GOtl18bFh38gGjqufhiuqoE4e57jYNE4EwLo0Y6YWzarxvtsQOL7EA-eYVCuQveLEcLNTgVUF5DyFxVD4Ueiv2pN5qZ1P1uw&usqp=CAc',
    type: 'Moisturizer',
    suitableFor: ['Combination Skin'],
    weatherCompatibility: { hot: true, humid: true },
    keyIngredients: ['Lady\'s Mantle', 'Oat Kernel'],
    benefits: ['Cooling', 'Refreshing', 'Gel texture'],
    routineType: 'Cosmetic'
  },

  // COMBINATION SKIN - Cleansers
  {
    id: 'cs-c-1',
    name: 'CeraVe Foaming Cleanser',
    description: 'Foaming gel cleanser for normal to oily skin.',
    price: 13.99,
    image: 'https://encrypted-tbn0.gstatic.com/shopping?q=tbn:ANd9GcRtFSlJn3zQBbBm0SonJCjTeHWMvafJMGy-ZT2SXjJoMLPeit86s2vqLE8i2bqBNd4fIkqLRW4KJYrbZVtJr5kgv5vv81VvNmsZS0zkXiciFAtXnsvul5jL',
    type: 'Cleanser',
    suitableFor: ['Combination Skin', 'Oily Skin'],
    weatherCompatibility: { hot: true, humid: true },
    keyIngredients: ['Ceramides', 'Niacinamide'],
    benefits: ['Foaming', 'Refreshing', 'Barrier protection'],
    routineType: 'Medical'
  },
  {
    id: 'cs-c-2',
    name: 'La Roche-Posay Effaclar Gel',
    description: 'Purifying foaming gel for oily sensitive skin.',
    price: 14.99,
    image: 'https://m.media-amazon.com/images/I/71zPXpbSDCL._SX355_.jpg',
    type: 'Cleanser',
    suitableFor: ['Combination Skin', 'Oily Skin'],
    weatherCompatibility: { hot: true, humid: true },
    keyIngredients: ['Zinc Pidolate'],
    benefits: ['Purifying', 'Oil control', 'Gentle'],
    routineType: 'Medical'
  },
  {
    id: 'cs-c-3',
    name: 'Cosrx Low pH Good Morning Cleanser',
    description: 'Gentle low pH cleanser with tea tree oil.',
    price: 11.99,
    image: 'https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcTzuR3cVwc1prtUwZ-Mmlkm0D3ip753iIr2VX73r15Rcz-nwbOpaymbJHNhWFb6qMCfyyYjGVQk-bB0yzvk_8DMI6n25NGJsBFU6qEyj9r8F2HJblrOPMmeSqVskpV09fm6ymWvySMdOA&usqp=CAc',
    type: 'Cleanser',
    suitableFor: ['Combination Skin'],
    weatherCompatibility: { hot: true, humid: true },
    keyIngredients: ['Tea Tree Oil', 'BHA'],
    benefits: ['Low pH', 'Gentle', 'Balancing'],
    routineType: 'Natural'
  },
  {
    id: 'cs-c-4',
    name: 'Neutrogena Fresh Foaming Cleanser',
    description: 'Oil-free foaming cleanser for fresh, clean skin.',
    price: 9.99,
    image: 'https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcRSe_uiA5ARvD3pXA8BeSb-Oisy0DaJmlxlmhWS3sy8FBHrPn7rBnXtS0jGZ-O1SE1oUlj_H6LcU6Zz5Zwb1lKIgCzxbNKx0zWSzNArYDNkQoLHUsFSVNY7rA',
    type: 'Cleanser',
    suitableFor: ['Combination Skin'],
    weatherCompatibility: { hot: true, humid: true },
    keyIngredients: ['Glycerin'],
    benefits: ['Oil-free', 'Fresh feeling', 'Deep cleansing'],
    routineType: 'Medical'
  },
  {
    id: 'cs-c-5',
    name: 'Simple Kind to Skin Refreshing Facial Wash',
    description: 'Refreshing gel wash with vitamin B5 and E.',
    price: 8.99,
    image: 'https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcSL4CIULKpu0BPtFOkiwEra-RDMkNduUqROIFK1GeDB-6MlpUQl_YTieZTEm_0D1eemmAlzn5RzIzPWqf8rA2pNsGS2k7DoGU9henVaObKwdytU7FKeXUA2',
    type: 'Face Wash',
    suitableFor: ['Combination Skin'],
    weatherCompatibility: { hot: true },
    keyIngredients: ['Vitamin B5', 'Vitamin E'],
    benefits: ['Refreshing', 'No harsh chemicals', 'Gentle'],
    routineType: 'Natural'
  },

  // COMBINATION SKIN - Toners
  {
    id: 'cs-t-1',
    name: "Paula's Choice Skin Balancing Pore Reducing Toner",
    description: 'Minimizes pores and balances combination skin.',
    price: 24.99,
    image: 'https://encrypted-tbn0.gstatic.com/shopping?q=tbn:ANd9GcSI-XDRPqoM6l4jtDHllZk7Xl-KWKKrns99dQlCsBliN8Bk8Sp9C1dwLIO1Rrr-U77isYkvbhqHdMhc9Sn0g78BNmPbyUMbDvA9ExCxPpoSs5JWLEaPXEtx',
    type: 'Toner',
    suitableFor: ['Combination Skin'],
    weatherCompatibility: { hot: true, humid: true },
    keyIngredients: ['Niacinamide', 'Ceramides'],
    benefits: ['Pore reducing', 'Balancing', 'Hydrating'],
    routineType: 'Medical'
  },
  {
    id: 'cs-t-2',
    name: 'Klairs Supple Preparation Toner',
    description: 'Essential hydrating toner for balanced skin.',
    price: 19.99,
    image: 'https://m.media-amazon.com/images/I/61K2fOs4y-S._SX466_.jpg',
    type: 'Toner',
    suitableFor: ['Combination Skin'],
    weatherCompatibility: { hot: true, cold: true },
    keyIngredients: ['Amino Acids', 'Hyaluronic Acid'],
    benefits: ['Hydrating', 'Balancing', 'Prepares skin'],
    routineType: 'Natural'
  },
  {
    id: 'cs-t-3',
    name: 'Pyunkang Yul Essence Toner',
    description: 'Minimalist essence toner for balanced hydration.',
    price: 14.99,
    image: 'https://m.media-amazon.com/images/I/51JKh7B+NxL._SX466_.jpg',
    type: 'Toner',
    suitableFor: ['Combination Skin'],
    weatherCompatibility: { hot: true, cold: true },
    keyIngredients: ['Barberry Root Extract'],
    benefits: ['Minimalist', 'Essence texture', 'Balancing'],
    routineType: 'Natural'
  },
  {
    id: 'cs-t-4',
    name: 'Cosrx AHA/BHA Clarifying Treatment Toner',
    description: 'Daily toner with AHA and BHA for gentle exfoliation.',
    price: 17.99,
    image: 'https://m.media-amazon.com/images/I/618OlEn9xML._SX466_.jpg',
    type: 'Toner',
    suitableFor: ['Combination Skin'],
    weatherCompatibility: { hot: true, humid: true },
    keyIngredients: ['AHA', 'BHA', 'Willow Bark'],
    benefits: ['Gentle exfoliation', 'Clarifying', 'Texture improvement'],
    routineType: 'Medical'
  },
  {
    id: 'cs-t-5',
    name: 'Benton Aloe BHA Toner',
    description: 'Soothing aloe toner with BHA for combination skin.',
    price: 13.99,
    image: 'https://m.media-amazon.com/images/I/71db--VYwXL._SL1500_.jpg',
    type: 'Toner',
    suitableFor: ['Combination Skin'],
    weatherCompatibility: { hot: true, humid: true },
    keyIngredients: ['Aloe Vera', 'BHA', 'Hyaluronic Acid'],
    benefits: ['Soothing', 'Gentle exfoliation', 'Hydrating'],
    routineType: 'Natural'
  },

  // COMBINATION SKIN - Serums
  {
    id: 'cs-s-1',
    name: 'The Ordinary Niacinamide 10% + Zinc 1%',
    description: 'High-strength niacinamide and zinc for oil control.',
    price: 6.99,
    image: 'https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcRcV_CfKXcO7tbqO8PSmLZzQIB2r0tKaS4Q4YTineo8SJBvHGfIfqxDPigPzSIBWn09WfUb8xu9h8_JdHPtxCLIoQFS_VqKyhwg1RUbl1AN72RVrcr31y_YLg',
    type: 'Serum',
    suitableFor: ['Combination Skin', 'Oily Skin'],
    weatherCompatibility: { hot: true, humid: true },
    keyIngredients: ['Niacinamide', 'Zinc'],
    benefits: ['Oil control', 'Pore minimizing', 'Blemish reduction'],
    routineType: 'Medical'
  },
  {
    id: 'cs-s-2',
    name: 'The Inkey List Hyaluronic Acid',
    description: 'Multi-weight hyaluronic acid for balanced hydration.',
    price: 8.99,
    image: 'https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcR-MCZxHTXV3DX9zmqHs1MnNv_rKUvKFnotHNp3_rD6Nyj04pqM0cSvqSU_w7pgF99Pupb_LKmQOotQAPGPdl82YwRi2LsF383vLNOU0Ah9krFKRQZ6BQbmLw',
    type: 'Serum',
    suitableFor: ['Combination Skin'],
    weatherCompatibility: { cold: true, dry: true },
    keyIngredients: ['Hyaluronic Acid'],
    benefits: ['Hydration', 'Plumping', 'Lightweight'],
    routineType: 'Medical'
  },
  {
    id: 'cs-s-3',
    name: 'Olay Regenerist Micro-Sculpting Serum',
    description: 'Advanced anti-aging serum suitable for combination skin.',
    price: 32.99,
    image: 'https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcSzfo9u6MD69MVPXd4pAAtEDLoOer-trnBl3PnbsIGUzeljtdvNvXPzT6zxwn12K3vgC70wW7vGu1auKBicrsMxLEF9yQR8vOAKqCakvhtlqq7IonBB2M5n0Q',
    type: 'Serum',
    suitableFor: ['Combination Skin'],
    weatherCompatibility: { hot: true, cold: true },
    keyIngredients: ['Amino-Peptides', 'Vitamin B3'],
    benefits: ['Anti-aging', 'Firming', 'Balancing'],
    routineType: 'Cosmetic'
  },
  {
    id: 'cs-s-4',
    name: 'COSRX Propolis Light Ampoule',
    description: 'Lightweight propolis serum for balanced hydration and glow.',
    price: 24.99,
    image: 'https://images.unsplash.com/photo-1570194065650-d99fb4bedf0a?w=400&h=400&fit=crop',
    type: 'Serum',
    suitableFor: ['Combination Skin'],
    weatherCompatibility: { hot: true, cold: true },
    keyIngredients: ['Propolis Extract', 'Hyaluronic Acid'],
    benefits: ['Glow', 'Soothing', 'Lightweight hydration'],
    routineType: 'Natural'
  },
  {
    id: 'cs-s-5',
    name: "Paula's Choice 10% Niacinamide Booster",
    description: 'High-strength niacinamide for pore refinement.',
    price: 44.99,
    image: 'https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcT1cWkQ68Oeqw3ogsc2jy3nSHJ18kkWdjT-joTziBBE4MkiSMoptb9ddsewIyxdP5JrPSJppXGMcjeim-1iI41QJl5Ahm5xovb2XmtEjE3qH3AUJbCHzTrq',
    type: 'Serum',
    suitableFor: ['Combination Skin'],
    weatherCompatibility: { hot: true, humid: true },
    keyIngredients: ['Niacinamide'],
    benefits: ['Pore minimizing', 'Brightening', 'Balancing'],
    routineType: 'Medical'
  },

  // COMBINATION SKIN - Sunscreens
  {
    id: 'cs-sun-1',
    name: 'Dot & Key Watermelon Cooling Sunscreen',
    description: 'Light formula sunscreen with watermelon for cooling effect.',
    price: 15.99,
    image: 'https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcRdXjNkATjgN0eCDhd0rsE05u5mA2sFddfAObokoDX2WFJRWm8Wb7LBLholoojtL3d8uR_L2DIdc-1C_vniagbBj3xQeUC8i-YMMWNVSJeeKCds47-Y3x9c',
    type: 'Sunscreen',
    suitableFor: ['Combination Skin'],
    weatherCompatibility: { hot: true, humid: true },
    keyIngredients: ['Watermelon', 'Niacinamide'],
    benefits: ['Cooling', 'Lightweight', 'Hydrating'],
    routineType: 'Cosmetic'
  },
  {
    id: 'cs-sun-2',
    name: 'Minimalist SPF',
    description: 'Lighter version sunscreen perfect for combination skin.',
    price: 12.99,
    image: 'https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcSK1oXOAV0XIgelc6wFZXXAycwgP8pMFjR8lAwWo42rLQ3uQAFCvRYCRlfd0812yZqZsfbsQyw9UaZdaaTsaBtmBR8dsWf80YxMCK10ua3m5uds47w8uL4NbQ',
    type: 'Sunscreen',
    suitableFor: ['Combination Skin'],
    weatherCompatibility: { hot: true, humid: true },
    keyIngredients: ['Broad Spectrum Filters'],
    benefits: ['Lightweight', 'Non-greasy', 'Fast absorbing'],
    routineType: 'Medical'
  },
  {
    id: 'cs-sun-3',
    name: 'Bioderma Photoderm AKN SPF',
    description: 'Mattifying sunscreen for combination to oily skin.',
    price: 22.99,
    image: 'https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcSpGJ-fAWdgA3e1hyshmyP0fwW-7IpqAxG5n0rFmLzw6cmF69oBJ6QRnuPS6ZrCwQfe_XlQL40nSw9jEvYLCKF3c74c68yK1EspaV7w6Qbv_m3B-xNd1EH4Zw',
    type: 'Sunscreen',
    suitableFor: ['Combination Skin', 'Oily Skin'],
    weatherCompatibility: { hot: true, humid: true },
    keyIngredients: ['Mattifying agents', 'Salicylic Acid'],
    benefits: ['Mattifying', 'Oil control', 'Anti-blemish'],
    routineType: 'Medical'
  },
  {
    id: 'cs-sun-4',
    name: 'La Roche-Posay Anthelios UVMune 400 Invisible Fluid',
    description: 'Ultra-high protection with invisible finish for combination skin.',
    price: 26.99,
    image: 'https://encrypted-tbn0.gstatic.com/shopping?q=tbn:ANd9GcSiBGzBPhWGFMGZIPsZzZ-lpNK4dvgM34ok4rAAMzhe3tX2tj-Ok2l1rGgWmSc6A-x-JrLWq2sGC4o6Z99humptBKLT5nwxXJ-3kNzYFQs8eShmW62TIHhCZA',
    type: 'Sunscreen',
    suitableFor: ['Combination Skin'],
    weatherCompatibility: { hot: true, humid: true },
    keyIngredients: ['UVMune 400', 'Mexoryl'],
    benefits: ['Ultra-high protection', 'Invisible', 'Lightweight'],
    routineType: 'Medical'
  },
  {
    id: 'cs-sun-5',
    name: 'Lotus Herbals Safe Sun',
    description: 'Non-oily sunscreen with herbal extracts.',
    price: 13.99,
    image: 'https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcTq3-LTO2ecAapnaZEQVUzaT62fU3Pxs1wW5lDxnSiBFzIa5_MgYJDVuPmrblgb_LJPwcYlGTekW-jyxmGXbgeQ3xgWejCWdZtT98ohspCyde0Xby1QQjBx',
    type: 'Sunscreen',
    suitableFor: ['Combination Skin'],
    weatherCompatibility: { hot: true },
    keyIngredients: ['Herbal Extracts'],
    benefits: ['Non-oily', 'Natural', 'Lightweight'],
    routineType: 'Natural'
  },

  // COMBINATION SKIN - Night Creams
  {
    id: 'cs-n-1',
    name: 'CeraVe PM Facial Moisturizing Lotion',
    description: 'Ultra-lightweight night lotion with niacinamide.',
    price: 16.99,
    image: 'https://m.media-amazon.com/images/I/61NsunzEV8L._SX466_.jpg',
    type: 'Night Cream',
    suitableFor: ['Combination Skin'],
    weatherCompatibility: { hot: true, cold: true },
    keyIngredients: ['Niacinamide', 'Ceramides', 'Hyaluronic Acid'],
    benefits: ['Lightweight', 'Barrier repair', 'Brightening'],
    routineType: 'Medical'
  },
  {
    id: 'cs-n-2',
    name: 'Clinique Moisture Surge Overnight Mask',
    description: 'Gel-cream overnight mask for combination skin.',
    price: 39.99,
    image: 'https://sdcdn.io/cl/cl_sku_7NR501_2400x2400_0.jpg?height=700px&width=700px',
    type: 'Night Cream',
    suitableFor: ['Combination Skin'],
    weatherCompatibility: { cold: true, dry: true },
    keyIngredients: ['Hyaluronic Acid', 'Aloe'],
    benefits: ['Gel texture', 'Hydrating', 'Non-greasy'],
    routineType: 'Cosmetic'
  },
  {
    id: 'cs-n-3',
    name: "Kiehl's Ultra Facial Oil-Free Gel-Cream",
    description: 'Oil-free gel-cream for balanced overnight hydration.',
    price: 32.99,
    image: 'https://images.unsplash.com/photo-1556228720-195a672e8a03?w=400&h=400&fit=crop',
    type: 'Night Cream',
    suitableFor: ['Combination Skin'],
    weatherCompatibility: { hot: true, humid: true },
    keyIngredients: ['Imperata Cylindrica Root', 'Antarcticine'],
    benefits: ['Oil-free', 'Gel texture', 'Hydrating'],
    routineType: 'Cosmetic'
  },
  {
    id: 'cs-n-4',
    name: 'The Ordinary Buffet',
    description: 'Multi-peptide formula for overnight skin health.',
    price: 16.99,
    image: 'https://m.media-amazon.com/images/I/510jeHjTlpL._SY355_.jpg',
    type: 'Night Cream',
    suitableFor: ['Combination Skin'],
    weatherCompatibility: { hot: true, cold: true },
    keyIngredients: ['Peptides', 'Amino Acids'],
    benefits: ['Multi-functional', 'Anti-aging', 'Lightweight'],
    routineType: 'Medical'
  },
  {
    id: 'cs-n-5',
    name: 'Laneige Water Sleeping Mask',
    description: 'Overnight hydration mask with gel texture.',
    price: 25.99,
    image: 'https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcR_IPO5lcVXnE9LGTD1cH6e2gzKaqD2QvkDCbU3xRu2aJt2mPZ82AABor5rfXR-zFm97OyRxEQ0ZMFmvmvmWBvMJQ8XnMhj',
    type: 'Night Cream',
    suitableFor: ['Combination Skin'],
    weatherCompatibility: { cold: true, dry: true },
    keyIngredients: ['Hydro Ionized Mineral Water'],
    benefits: ['Gel texture', 'Overnight hydration', 'Refreshing'],
    routineType: 'Cosmetic'
  },

  // DRY SKIN - Moisturizers
  {
    id: 'ds-m-1',
    name: 'CeraVe Moisturizing Cream',
    description: 'Rich cream with ceramides and hyaluronic acid for intense hydration.',
    price: 15.99,
    image: 'https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcQB6aJFF6hMK1b19mYzJ69iptunSpjnFY-YXfUiK4mDZMbDeuNdeWu_3KDJVQTJfLFt_taG4TboiBt0iIkNKdijQ2qzIZACX_gl1PfaWXuBgiYkmgTmVML2nhjZ3_J4qmDARlU5_dw&usqp=CAc',
    type: 'Moisturizer',
    suitableFor: ['Dry Skin'],
    weatherCompatibility: { cold: true, dry: true },
    keyIngredients: ['Ceramides', 'Hyaluronic Acid'],
    benefits: ['Deep hydration', 'Barrier repair', 'Rich texture'],
    routineType: 'Medical'
  },
  {
    id: 'ds-m-2',
    name: 'Cetaphil Moisturising Cream',
    description: 'Deep hydrating cream for very dry skin.',
    price: 14.99,
    image: 'https://images.unsplash.com/photo-1556228720-195a672e8a03?w=400&h=400&fit=crop',
    type: 'Moisturizer',
    suitableFor: ['Dry Skin'],
    weatherCompatibility: { cold: true, dry: true },
    keyIngredients: ['Glycerin', 'Sweet Almond Oil'],
    benefits: ['Deep hydration', 'Rich texture', 'Long-lasting'],
    routineType: 'Medical'
  },
  {
    id: 'ds-m-3',
    name: 'La Roche-Posay Toleriane Double Repair Moisturizer',
    description: 'Prebiotic moisturizer for sensitive dry skin.',
    price: 19.99,
    image: 'https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcSbQ55AccU2OX2aRkmcNSIccOZEeg0_ZRm2YN8lMMUHz-4t-0yQL1jGbgXwZ_PmJLLQ4_MnNz9Bx0jngi3sP4iJhcFgmGhDs9rVwNkC0ua9mIfJOGGktrw9',
    type: 'Moisturizer',
    suitableFor: ['Dry Skin'],
    weatherCompatibility: { cold: true, dry: true },
    keyIngredients: ['Ceramides', 'Niacinamide', 'Prebiotic'],
    benefits: ['Barrier repair', 'Prebiotic care', 'Intense hydration'],
    routineType: 'Medical'
  },
  {
    id: 'ds-m-4',
    name: 'Vanicream Moisturizing Cream',
    description: 'Gentle, fragrance-free cream for sensitive dry skin.',
    price: 16.99,
    image: 'https://encrypted-tbn0.gstatic.com/shopping?q=tbn:ANd9GcQuYX-mAdM9HgGya22ZFf9o-gHnITraBxc_8o2i0a1lS6OrkNxA87TPTkgrF4RxTJV2X5KJKiD7iYprAVF02gq5bITivWK0mrzhQj3aILRZ7ot9jayCbvevDg',
    type: 'Moisturizer',
    suitableFor: ['Dry Skin', 'Sensitive Skin'],
    weatherCompatibility: { cold: true, dry: true },
    keyIngredients: ['Petrolatum', 'Sorbitol'],
    benefits: ['Fragrance-free', 'Gentle', 'Intense moisture'],
    routineType: 'Medical'
  },
  {
    id: 'ds-m-5',
    name: 'First Aid Beauty Ultra Repair Cream',
    description: 'Intensive repair cream with colloidal oatmeal.',
    price: 34.99,
    image: 'https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcSWzXqeSDkqopYdP4I1zscitOIwR1-xds8htmC7EGFZiF5pkVlqCS2p0xWlhPEYx2mI7yhnk_tptL2OndyUc1homRch2ScLKcGJ5CzIrgldsI7XuHHEczRz',
    type: 'Moisturizer',
    suitableFor: ['Dry Skin'],
    weatherCompatibility: { cold: true, dry: true },
    keyIngredients: ['Colloidal Oatmeal', 'Shea Butter'],
    benefits: ['Intensive repair', 'Soothing', 'Rich hydration'],
    routineType: 'Medical'
  },

  // DRY SKIN - Cleansers
  {
    id: 'ds-c-1',
    name: 'CeraVe Hydrating Cleanser',
    description: 'Non-foaming cleanser that preserves skin moisture.',
    price: 13.99,
    image: 'https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcRHBQrWefCNz0FXnQypq3VkAeL1qLYnVoYCZU_embveKBTd-T7vZElhPKnTn3VXrZd2QIopCAe4HYeeDRmBNTaVTADf1xYGfKJOHR7arjWIcS41dcI2n3kySmHby9UgOG-QJwL79g&usqp=CAc',
    type: 'Cleanser',
    suitableFor: ['Dry Skin'],
    weatherCompatibility: { cold: true, dry: true },
    keyIngredients: ['Ceramides', 'Hyaluronic Acid'],
    benefits: ['Non-foaming', 'Hydrating', 'Gentle'],
    routineType: 'Medical'
  },
  {
    id: 'ds-c-2',
    name: 'Cetaphil Gentle Skin Cleanser',
    description: 'Ultra-gentle cleanser for dry, sensitive skin.',
    price: 12.99,
    image: 'https://images.unsplash.com/photo-1556228720-195a672e8a03?w=400&h=400&fit=crop',
    type: 'Cleanser',
    suitableFor: ['Dry Skin', 'Sensitive Skin'],
    weatherCompatibility: { cold: true, dry: true },
    keyIngredients: ['Glycerin'],
    benefits: ['Ultra-gentle', 'Non-stripping', 'pH balanced'],
    routineType: 'Medical'
  },
  {
    id: 'ds-c-3',
    name: 'La Roche-Posay Toleriane Hydrating Gentle Cleanser',
    description: 'Creamy cleanser that maintains skin barrier.',
    price: 14.99,
    image: 'https://m.media-amazon.com/images/I/51Dk9TsVZ+L._SY355_.jpg',
    type: 'Cleanser',
    suitableFor: ['Dry Skin'],
    weatherCompatibility: { cold: true, dry: true },
    keyIngredients: ['Ceramide-3', 'Niacinamide'],
    benefits: ['Creamy texture', 'Barrier protection', 'Soothing'],
    routineType: 'Medical'
  },
  {
    id: 'ds-c-4',
    name: 'Neutrogena Hydro Boost Foaming Gel',
    description: 'Gentle foaming gel with hyaluronic acid.',
    price: 10.99,
    image: 'https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcTECxpwatYbUchZvAO1QPver2ZbQCrVi0d4mk2tk97foL6_iLVByw_x0OhqBfAxrV4oobLq9rWkIeUFuyfT2iUB01nQgqMIsuSr9_lbTnv8F3C8QWk-VGnH',
    type: 'Cleanser',
    suitableFor: ['Dry Skin'],
    weatherCompatibility: { cold: true },
    keyIngredients: ['Hyaluronic Acid'],
    benefits: ['Gentle foaming', 'Hydrating', 'Refreshing'],
    routineType: 'Medical'
  },
  {
    id: 'ds-c-5',
    name: 'The Face Shop Rice Water Bright Cleansing Foam',
    description: 'Brightening cleanser with rice water (use carefully on dry skin).',
    price: 11.99,
    image: 'https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcRHG1s4d0FelmfoQgQbllNNbJBrzaYoHTJWM5-b_P-YOHazT8FSRVF_UAYKJNIWquPlLGLvXycl1XqQx7oc6G4ZFVyLiCREYWNjSIdaugVbRY-zuze9F6anxN2sRJubtf4f0ateS8_IJIJP&usqp=CAc',
    type: 'Face Wash',
    suitableFor: ['Dry Skin'],
    weatherCompatibility: { hot: true },
    keyIngredients: ['Rice Water'],
    benefits: ['Brightening', 'Natural', 'Gentle'],
    routineType: 'Natural'
  },

  // DRY SKIN - Toners
  {
    id: 'ds-t-1',
    name: 'Klairs Supple Preparation Unscented Toner',
    description: 'Deeply hydrating toner without essential oils.',
    price: 19.99,
    image: 'https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcQyzED4J29NzVJMaD3TjfpgVdsClyNMSaCsbIWHyZ4EcjQeCJA1dZst9VKXJOfaxpldS4tY6BLywHfZhFNEAFBnllbqskyr83G6TigSxFMfCpW78mQakwmorA',
    type: 'Toner',
    suitableFor: ['Dry Skin', 'Sensitive Skin'],
    weatherCompatibility: { cold: true, dry: true },
    keyIngredients: ['Amino Acids', 'Hyaluronic Acid'],
    benefits: ['Deep hydration', 'Unscented', 'Calming'],
    routineType: 'Natural'
  },
  {
    id: 'ds-t-2',
    name: 'Hada Labo Gokujyun Premium Lotion',
    description: 'Super hydrating lotion with 5 types of hyaluronic acid.',
    price: 17.99,
    image: 'https://m.media-amazon.com/images/I/71976yktlzL._SY879_.jpg',
    type: 'Toner',
    suitableFor: ['Dry Skin'],
    weatherCompatibility: { cold: true, dry: true },
    keyIngredients: ['5 Types Hyaluronic Acid'],
    benefits: ['Super hydrating', 'Plumping', 'Multi-layer moisture'],
    routineType: 'Medical'
  },
  {
    id: 'ds-t-3',
    name: 'Cosrx Hydrium Green Tea Aqua Soothing Toner',
    description: 'Soothing hydrating toner with green tea.',
    price: 15.99,
    image: 'https://m.media-amazon.com/images/I/61e2iyhXxeL._SX466_.jpg',
    type: 'Toner',
    suitableFor: ['Dry Skin'],
    weatherCompatibility: { cold: true, dry: true },
    keyIngredients: ['Green Tea', 'Panthenol'],
    benefits: ['Soothing', 'Hydrating', 'Calming'],
    routineType: 'Natural'
  },
  {
    id: 'ds-t-4',
    name: 'Isntree Hyaluronic Acid Toner',
    description: 'Multi-molecular hyaluronic acid for maximum hydration.',
    price: 16.99,
    image: 'https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcQSdraApN1TDdrMT1dXaCLLgMOWZwc9p-qyrmuSRJKs5--2RUa4xA3T1uXS98dJNKqe53yQlyG2A1_D9L3jVnqvIgfhYyl_zvvZJJB5qa9ZkK4nU196cm5v1w',
    type: 'Toner',
    suitableFor: ['Dry Skin'],
    weatherCompatibility: { cold: true, dry: true },
    keyIngredients: ['Hyaluronic Acid'],
    benefits: ['Maximum hydration', 'Plumping', 'Deep moisture'],
    routineType: 'Medical'
  },
  {
    id: 'ds-t-5',
    name: 'Benton Aloe BHA Skin Toner',
    description: 'Aloe-based toner with gentle hydration.',
    price: 13.99,
    image: 'https://m.media-amazon.com/images/I/71db--VYwXL._SY355_.jpg',
    type: 'Toner',
    suitableFor: ['Dry Skin'],
    weatherCompatibility: { cold: true, dry: true },
    keyIngredients: ['Aloe Vera', 'BHA'],
    benefits: ['Soothing', 'Hydrating', 'Gentle'],
    routineType: 'Natural'
  },

  // DRY SKIN - Serums
  {
    id: 'ds-s-1',
    name: 'The Ordinary Hyaluronic Acid 2% + B5',
    description: 'Multi-depth hyaluronic acid for intense hydration.',
    price: 7.99,
    image: 'https://m.media-amazon.com/images/I/41QX2rGH4XL._SY879_.jpg',
    type: 'Serum',
    suitableFor: ['Dry Skin'],
    weatherCompatibility: { cold: true, dry: true },
    keyIngredients: ['Hyaluronic Acid', 'Vitamin B5'],
    benefits: ['Intense hydration', 'Plumping', 'Multi-layer moisture'],
    routineType: 'Medical'
  },
  {
    id: 'ds-s-2',
    name: 'La Roche-Posay Hyalu B5 Serum',
    description: 'Anti-aging serum with hyaluronic acid and vitamin B5.',
    price: 42.99,
    image: 'https://m.media-amazon.com/images/I/71OyWl-fdOL._SY355_.jpg',
    type: 'Serum',
    suitableFor: ['Dry Skin'],
    weatherCompatibility: { cold: true, dry: true },
    keyIngredients: ['Hyaluronic Acid', 'Vitamin B5', 'Madecassoside'],
    benefits: ['Anti-aging', 'Deep hydration', 'Repairing'],
    routineType: 'Medical'
  },
  {
    id: 'ds-s-3',
    name: 'Vichy Mineral 89',
    description: 'Fortifying serum with volcanic water for dry skin.',
    price: 29.99,
    image: 'https://m.media-amazon.com/images/I/817YEiXqQ5L._SY355_.jpg',
    type: 'Serum',
    suitableFor: ['Dry Skin'],
    weatherCompatibility: { cold: true, dry: true },
    keyIngredients: ['Volcanic Water', 'Hyaluronic Acid'],
    benefits: ['Fortifying', 'Hydrating', 'Plumping'],
    routineType: 'Medical'
  },
  {
    id: 'ds-s-4',
    name: "Paula's Choice Calm Redness Relief Repairing Serum",
    description: 'Soothing serum for dry, sensitive skin.',
    price: 38.99,
    image: 'https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcRQGU815cr-gROwlzAiq32LzXxRAdkEYghf49p727hDVuhP4Hw8wJNuoHFi4DHvXhLJTgTbs7VSeXMucwPVBCY9hiRUuH2pw_wHBDDJOC-vpssBUWNcPDk',
    type: 'Serum',
    suitableFor: ['Dry Skin', 'Sensitive Skin'],
    weatherCompatibility: { cold: true, dry: true },
    keyIngredients: ['Ceramides', 'Allantoin'],
    benefits: ['Redness relief', 'Calming', 'Barrier repair'],
    routineType: 'Medical'
  },
  {
    id: 'ds-s-5',
    name: 'Drunk Elephant Lala Retro Whipped Cream',
    description: 'Rich serum-cream hybrid for intense hydration.',
    price: 60.99,
    image: 'https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcQk6dpd5QknUtoAOkipBGM0HO6o2hIqAC1gIYKG7XrC8aazvco9jBUY2bcWaSivGBL25uyAhNcxGIWFZC5KOH_QGxYsKVpHRC1oq5P5qs6DXObzoy7HSIL7sA',
    type: 'Serum',
    suitableFor: ['Dry Skin'],
    weatherCompatibility: { cold: true, dry: true },
    keyIngredients: ['Ceramides', 'Plant Oils'],
    benefits: ['Rich hydration', 'Barrier support', 'Nourishing'],
    routineType: 'Cosmetic'
  },

  // DRY SKIN - Sunscreens
  {
    id: 'ds-sun-1',
    name: 'La Roche-Posay Anthelios Melt-In Milk SPF',
    description: 'Hydrating sunscreen with melt-in texture.',
    price: 35.99,
    image: 'https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcTgFls2GbX_B6jsTTkQkILLXDCzbLeKM9vAxQ9-p8ZWHE9VvuFoPM3iy6OgnavCa5NftuUdxstOcreinWGZi_XznkP8wrrESuEeu_FO_Ua9hDeE2thzslrzdw',
    type: 'Sunscreen',
    suitableFor: ['Dry Skin'],
    weatherCompatibility: { hot: true, cold: true },
    keyIngredients: ['Cell-Ox Shield', 'Antioxidants'],
    benefits: ['Hydrating', 'Melt-in texture', 'Antioxidant protection'],
    routineType: 'Medical'
  },
  {
    id: 'ds-sun-2',
    name: 'Bioderma Photoderm Aquafluide SPF 50+',
    description: 'Light fluid sunscreen suitable for dry skin.',
    price: 19.99,
    image: 'https://m.media-amazon.com/images/I/51RAv5Q31fL._SY355_.jpg',
    type: 'Sunscreen',
    suitableFor: ['Dry Skin'],
    weatherCompatibility: { hot: true },
    keyIngredients: ['Cellular Bioprotection'],
    benefits: ['Light texture', 'Non-greasy', 'High protection'],
    routineType: 'Medical'
  },
  {
    id: 'ds-sun-3',
    name: 'ISDIN Fusion Water SPF',
    description: 'Ultra-light water-phase sunscreen.',
    price: 38.99,
    image: 'https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcTiElCJKuJptWPK84V2pHxuDdpGanGl7S8zjP_x-M2s0FLu2V1fq0W8DjUFaknR8fi8OVoAMyKhqcsPJqsXCTbYcqCNimuG5DrpGH8-mCFsO1tYVKLpuKs1BP4',
    type: 'Sunscreen',
    suitableFor: ['Dry Skin'],
    weatherCompatibility: { hot: true },
    keyIngredients: ['Water-based formula'],
    benefits: ['Ultra-light', 'Fast absorption', 'Hydrating'],
    routineType: 'Medical'
  },
  {
    id: 'ds-sun-4',
    name: 'Minimalist 5% Niacinamide + 1% Zinc SPF',
    description: 'Mild sunscreen with niacinamide for dry skin.',
    price: 12.99,
    image: 'https://m.media-amazon.com/images/I/5166sMOwu5L._SY355_.jpg',
    type: 'Sunscreen',
    suitableFor: ['Dry Skin'],
    weatherCompatibility: { hot: true },
    keyIngredients: ['Niacinamide', 'Zinc'],
    benefits: ['Brightening', 'Gentle', 'Hydrating'],
    routineType: 'Medical'
  },
  {
    id: 'ds-sun-5',
    name: 'CeraVe Hydrating Mineral Sunscreen',
    description: 'Mineral sunscreen with ceramides for dry skin.',
    price: 16.99,
    image: 'https://encrypted-tbn0.gstatic.com/shopping?q=tbn:ANd9GcR29mFcKsNpWa995UkwPRX9ZtRR3qzwEk1lrQx6ZvdWQBX7f6JxbFi8s2UZzMDb9vPizF4fBcKzJzlgj6OXLmZNlW8tTYRwRMFVRKSCWnqJHn5wC6gC1_uo',
    type: 'Sunscreen',
    suitableFor: ['Dry Skin'],
    weatherCompatibility: { hot: true, cold: true },
    keyIngredients: ['Zinc Oxide', 'Ceramides'],
    benefits: ['Mineral protection', 'Hydrating', 'Barrier support'],
    routineType: 'Medical'
  },

  // DRY SKIN - Night Creams
  {
    id: 'ds-n-1',
    name: 'CeraVe Skin Renewing Night Cream',
    description: 'Peptide-infused night cream for dry skin renewal.',
    price: 18.99,
    image: 'https://m.media-amazon.com/images/I/71r7bLsvaVL._SY355_.jpg',
    type: 'Night Cream',
    suitableFor: ['Dry Skin'],
    weatherCompatibility: { cold: true, dry: true },
    keyIngredients: ['Peptides', 'Ceramides', 'Hyaluronic Acid'],
    benefits: ['Overnight renewal', 'Rich texture', 'Anti-aging'],
    routineType: 'Medical'
  },
  {
    id: 'ds-n-2',
    name: 'Laneige Water Sleeping Mask',
    description: 'Rich overnight mask for intense hydration.',
    price: 25.99,
    image: 'https://m.media-amazon.com/images/I/41Mnh4kjSyL._AC_UL480_FMwebp_QL65_.jpg',
    type: 'Night Cream',
    suitableFor: ['Dry Skin'],
    weatherCompatibility: { cold: true, dry: true },
    keyIngredients: ['Hydro Ionized Mineral Water'],
    benefits: ['Rich hydration', 'Overnight treatment', 'Purifying'],
    routineType: 'Cosmetic'
  },
  {
    id: 'ds-n-3',
    name: "Kiehl's Ultra Facial Cream",
    description: 'Rich 24-hour moisture cream for dry skin.',
    price: 35.99,
    image: 'https://m.media-amazon.com/images/I/61271b8GniL._AC_UL480_FMwebp_QL65_.jpg',
    type: 'Night Cream',
    suitableFor: ['Dry Skin'],
    weatherCompatibility: { cold: true, dry: true },
    keyIngredients: ['Squalane', 'Glacial Glycoprotein'],
    benefits: ['24-hour moisture', 'Rich texture', 'Protective'],
    routineType: 'Cosmetic'
  },
  {
    id: 'ds-n-4',
    name: 'First Aid Beauty Ultra Repair Cream',
    description: 'Intensive overnight repair cream.',
    price: 34.99,
    image: 'https://m.media-amazon.com/images/I/61BSynl2O2L._AC_UL480_FMwebp_QL65_.jpg',
    type: 'Night Cream',
    suitableFor: ['Dry Skin'],
    weatherCompatibility: { cold: true, dry: true },
    keyIngredients: ['Colloidal Oatmeal', 'Shea Butter'],
    benefits: ['Intensive repair', 'Calming', 'Rich nourishment'],
    routineType: 'Medical'
  },
  {
    id: 'ds-n-5',
    name: "Paula's Choice Omega+ Complex Moisturizer",
    description: 'Omega-rich night moisturizer for dry skin.',
    price: 39.99,
    image: 'https://m.media-amazon.com/images/I/61oTQanafHL._SY355_.jpg',
    type: 'Night Cream',
    suitableFor: ['Dry Skin'],
    weatherCompatibility: { cold: true, dry: true },
    keyIngredients: ['Omega Fatty Acids', 'Antioxidants'],
    benefits: ['Omega nourishment', 'Barrier repair', 'Anti-aging'],
    routineType: 'Medical'
  }
];